### ISSUE TITLE
Can't install with Node v14

### ISSUE THREAD

**Issue by sercanov** [appsignal/appsignal-nodejs#1001]
I'm using Strapi v3 and it enforces Node v14, when I try to install AppSignal Node package, it throws;

```
error node-gyp@10.0.1: The engine "node" is incompatible with this module. Expected version "^16.14.0 || >=18.0.0". Got "14.19.3"
error Found incompatible module.
```

Any workarounds?

**Comment by unflxw** [comment]
Hi @sercanov,

We use OpenTelemetry, which itself does not support Node.js 14 anymore. [Node.js 14 has been unsupported for almost three years](https://endoflife.date/nodejs) at this point. I'm afraid there is no workaround. The only solution would be to upgrade Node.js (and Strapi) as needed.
