### ISSUE TITLE
Current version of "instrumentation-ioredis" uses non-existing package "@types/ioredis"

### ISSUE THREAD

**Issue by Crismon96** [appsignal/appsignal-nodejs#1068]
The package `@types/ioredis` doesn't exist on the nom registry anymore. A newer version of `instrumentation-ioredis` respects that and drops the dependency. We currently have to patch the dependency to `instrumentation-ioredis` because we can't install the package. It would be great if you could update to a working version of the package so that we can remove the patch.

Here you see the dependency of `@appsignal/nodejs@3.0.25",`:
```
 "node_modules/@opentelemetry/instrumentation-ioredis": {
      "version": "0.35.3",
      "resolved": "https://registry.npmjs.org/@opentelemetry/instrumentation-ioredis/-/instrumentation-ioredis-0.35.3.tgz",
      "integrity": "sha512-QIjSbC7JmbR3dVQtWg/PF5uOuawIyvD4KQIj5PJcYFfJQq0nZ+agiJ6KVjeK3rWPXbop6zGvU66d79r48j2rKA==",
      "dependencies": {
        "@opentelemetry/instrumentation": "^0.45.1",
        "@opentelemetry/redis-common": "^0.36.1",
        "@opentelemetry/semantic-conventions": "^1.0.0",
        "@types/ioredis4": "npm:@types/ioredis@^4.28.10"
      },
      "engines": {
        "node": ">=14"
      },
      "peerDependencies": {
        "@opentelemetry/api": "^1.3.0"
      }
    },
    ```
    
    `@types/ioredis` doesn't exist anymore.

**Comment by tombruijn** [comment]
Hi @Crismon96, thanks for the report! We'll have a look to see if we can upgrade the package.

**Comment by tombruijn** [comment]
Fix released in Node.js package 3.4.7
