### ISSUE TITLE
Appsignal requires options parameter

### ISSUE THREAD

**Issue by simonrussell** [appsignal/appsignal-nodejs#125]
In the documentation (and reading through the code) it seems like the intent is that all parameters to the main `Appsignal` entrypoint are optional -- they can be supplied with environment variables.  However, the Typescript definition doesn't let you leave out the argument entirely, and if you do supply it, you are required to give app name and API key -- these values will override the environment variables.

I'd like to use this with app name fixed in the code, but the API key and environment name supplied in environment variables.  I could do this by hand (`Process.env`) but it seems like this is an oversight?

**Comment by xadamy** [comment]
@simonrussell  You are correct that this should have been the case but for some reason was not, and that was also fixed in `0.3.3`.
