### ISSUE TITLE
npx Install Script

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-nodejs#131]
Users currently install the core library and integrations separately:

```
yarn add @appsignal/nodejs @appsignal/express
```

This allows the library to be modular, reducing size and complexity of the core library as well as enabling us to prefer framework-specific integrations where possible (like the `express` integration) rather introducing complex monkey-patching solutions that could conflict with other modules:

```
express().use(expressMiddleware(appsignal))
```

Such an integration is not possible to do automatically, as it requires the user to instantiate an object that is in a lexical scope we can't access.

However, this means that users have to remember to install any integrations, and in some projects with a large amount of dependencies, this could amount to quite a number of additional packages to remember to install.

This proposal is to add an [`npx` command](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) to install, rather than use `npm install`/`yarn add` directly (the user could still do this if they know what the're doing).

```
npx appsignal
```

The script would do the following:

- Add the latest `@appsignal/nodejs` to `package.json`
- Read `package.json` and add integrations for known packages to `package.json`
- Run `yarn install`

This script could be run again at any time to install packages for any new modules the user might have installed.

With this change, we'd like to achieve the following:

- Improve user convenience

## Next Steps

- [ ] Gather requirements
- [ ] Discuss potential technical solutions
- [ ] Schedule for implementation

**Comment by thijsc** [comment]
Sounds good. Some thoughts:

- Would make sense to have this be the install command as well. Could you pass in the API key and generate config straight away?
- What would happen if we add support for new libraries, would one have to re-run this command?

**Comment by xadamy** [comment]
> Could you pass in the API key and generate config straight away?

Yes, and I think this is a good idea, if at the very least just to print the populated environment variables to stdout.

**Comment by xadamy** [comment]
From the call this morning, myself and @wesoudshoorn have decided on the following flow:

- "whats your push api key?
- add the package to package.json (what happens when both yarn.lock and package-lock.json are present?)
- "looking for appsignal supported packages..."
- "we found n packages. do you want to install?"
  - if yes, `npm install`
  - if no, print a list anyway (`npm install x x x`)
- list ways to add key to the environment, link to docs page
  - `export APPSIGNAL_PUSH_API_KEY="<key>"`
  - add to dotenv file (can we write to this?)
  - add to your heroku dashboard etc (note to self: check docs for cloud platform env var installing)
  - can we copy and paste back from terminal session?
