### ISSUE TITLE
Port extension code to Rust

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#140]
Long term, it'd be nice to port the code in `appsignal_extension.cpp` to Rust to keep it consistent with the rest of the agent. No doubt we could use the additional memory safety here also.

[Neon](https://github.com/neon-bindings/neon) would de a good option to enable this. Currently, however, N-API support is still [in the early stages](https://github.com/neon-bindings/neon/issues/444) (we rely on N-API exclusively to interface Node with the agent).

An important part of the problem here is what happens when `rustc` is not installed. In Heroku boxes, for example, `rustc`isn't installed in the default buildpack, so people installing the agent will be unable to compile the extension.

**Comment by Brooooooklyn** [comment]
try with https://github.com/napi-rs/napi-rs ?
