### ISSUE TITLE
Nuxt.js integration

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#143]
https://nuxtjs.org

**Comment by tombruijn** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/27064419256

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/16410700088928

**Comment by luismiramirez** [comment]
Not supported by default. Users can add OpenTelemetry-compliant instrumentations to v3 using the `additionalInstrumentations` config option. See: https://docs.appsignal.com/nodejs/3.x/configuration/options.html#option-additionalinstrumentations

**Comment by unflxw** [comment]
The comment above does not seem to be correct. As far as I can tell, there is no OpenTelemetry instrumentation for Nuxt.js.

**Comment by unflxw** [comment]
To clarify, there is no OpenTelemetry instrumentation for Nuxt.js.

We have filed a feature request for Nuxt.js support internally. Do let us know at support@appsignal.com if you'd be interested in it.
