### ISSUE TITLE
ECMAScript module support

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#17]
Yesterday, [support for ECMAScript modules was merged into Node.js](https://twitter.com/MylesBorins/status/1194375751774064647). This represents a fundamental change in the way that modules work in Node.js, and subsequently, a change that will require us to add support for it in this library in order to support future modules.

Currently, when importing a CommonJS module with `require()`, we need to be able to monkeypatch Node modules at require time in order to instrument them, and traditionally this has been done by monkeypatching the `Module` internals themselves in order to catch and modify modules that we need to integrate into.

ECMAScript modules has a different method for handling this that we will also need to take into account. [This YouTube talk](https://www.youtube.com/watch?v=omOtwqffhck) outlines the steps necessary.

**Comment by feross** [comment]
Our app runs on Node 15 with native ESM and we'd love to see support for this. Node 16 will be released on April 20, 2021, and it will increase the number of people using native ESM by quite a lot.

Would be amazing to see AppSignal be one of the first to support native ESM.

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700089320 (Private link)

**Comment by zarianec** [comment]
Is there any information or time estimates for this feature? ESM is getting more and more popular in the NodeJS ecosystem.
