### ISSUE TITLE
Generic HTTP/HTTPS instrumentation

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#22]
Related to #21. We'll need to leverage our module instrumentation abstraction (buzzwords!) to instrument the core Node.js HTTP/HTTPS module.

The point of this would be mainly to create and close the top-most `Span` for the current context (could be a `RootSpan` in a single machine trace, could be a `ChildSpan` in a multi machine trace) when an HTTP request is started and finish.

This will effectively allow us to integrate at a low-level and offer _some_ out-of-the-box compatibility for all the major HTTP frameworks. I assume there will still be some logic that is framework specific for other tasks, and we can keep that logic in specific packages (e.g. `@appsignal/express` for `express`).

TODO:

- [x] HTTP Incoming Requests (#48)
- [x] HTTP Outgoing Requests
- [x] HTTPS Incoming Requests
- [x] HTTPS Outgoing Requests
- [ ] HTTP2 Incoming Requests
- [ ] HTTP2 Outgoing Requests

**Comment by luismiramirez** [comment]
Supported in v3
