### ISSUE TITLE
bull Integration

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#245]
https://github.com/OptimalBits/bull

**Comment by xadamy** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700007462

**Comment by luismiramirez** [comment]
Not supported by default. Users can add OpenTelemetry-compliant instrumentations to v3 using the additionalInstrumentations config option. See: https://docs.appsignal.com/nodejs/3.x/configuration/options.html#option-additionalinstrumentations
