### ISSUE TITLE
Extension fails to build with musl libc

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#29]
As mentioned in https://github.com/appsignal/appsignal-agent/pull/484 (private issue), the extension is currently unable to build against musl libc.

This affects all users installing in an Alpine Linux environment.

**Comment by xadamy** [comment]
As a workaround, users can add the following to their `Dockerfile`, which will allow the extension to build on Alpine Linux:

```
FROM node:alpine

RUN apk add --no-cache --virtual .gyp python make g++ \
    && npm install [ your npm dependencies here ] \
    && apk del .gyp
```

See https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#node-gyp-alpine.

A proper fix for this is incoming.

**Comment by tomaspinho** [comment]
Hi @xadamy . Just encountered this issue. The `appsignal-agent` shared library cannot be loaded in an Alpine Linux container because there are missing functions from glibc. Could we have a version of the agent that works with musl?

**Comment by xadamy** [comment]
@tomaspinho The agent already has a `musl` build, but we currently have an issue with the extension (the C++ bridge between the integration and the agent) that prevents it from compiling with `musl`. We're looking into it but I can't give a timeframe currently, however it should still work if you follow the instructions [above](https://github.com/appsignal/appsignal-nodejs/issues/29#issuecomment-586186959). Does this work for you?

**Comment by tomaspinho** [comment]
The extension builds correctly, however for some reason the binary downloaded from your servers is built against glibc, not musl. So the extension fails loading it as a shared library on runtime.

**Comment by xadamy** [comment]
@tomaspinho Ah! In which case, there might be something wrong with our installation script. Could you try setting an environment variable for me: can you set `APPSIGNAL_BUILD_FOR_MUSL` to `true` before the package is installed, and let me know whether this gets you the right binary?

**Comment by tomaspinho** [comment]
Just debugged this, yes, there's a bug in `getMetadataForTarget` in `packages/nodejs/scripts/extension.js`: the key `musl_override` should actually be `muslOverride`, as defined in `packages/nodejs/scripts/report.js`.

**Comment by tomaspinho** [comment]
@xadamy please see https://github.com/appsignal/appsignal-nodejs/pull/91 for a fix

**Comment by tomaspinho** [comment]
Also, I would suggest considering https://github.com/appsignal/appsignal-nodejs/pull/92/files to take care of musl installations automatically instead of relying on user override

**Comment by xadamy** [comment]
@tomaspinho Thanks, all the above look like good fixes! 👍I will push a new version to `npm` sometime later today that incorporates these fixes. In the meantime, we'd love to send you the gift of [stroopwafels](https://en.wikipedia.org/wiki/Stroopwafel) by way of thanks. Please drop an email to support@appsignal.com mentioning this issue and we'll get those arranged for you.

**Comment by tomaspinho** [comment]
No worries, we're a client of yours at [Remote](remote.com). Was just making this run in our environment :)

**Comment by xadamy** [comment]
I've just published `0.3.0`, which includes @tomaspinho 's fixes for the issue starting [here](https://github.com/appsignal/appsignal-nodejs/issues/29#issuecomment-611615901). 🎉

**Comment by soufian044** [comment]
I having some issue running npm install, the extension script fails [here ](https://github.com/appsignal/appsignal-nodejs/blob/26ce3dafbc932f9caf66a158e83b8dbadf94e46a/packages/nodejs-ext/scripts/extension.js#L84) , does this has something to do with this issue ? 

![image](https://user-images.githubusercontent.com/10144036/80204840-e1e6c580-8629-11ea-9109-f8a07532844d.png)

thanks guys

**Comment by xadamy** [comment]
@soufian044 This isn't actually related, we don't currently offer Windows builds of the agent (it looks from your screenshot like you are running this from Windows), so thats why you're seeing this error. I will tighten up the extension fetching script to give a more friendly error message, but this module cannot be run from Windows at this time.

**Comment by soufian044** [comment]
@xadamy : sorry if this is not the right place to ask but just to explain more , i get this error when adding the appsignal nodejs dependencies , indeed i'm running a project locally on windows. when setting up everything as i suppose to , the moment tha api receive a request i get this error so i thought maybe it has something to do with the missing dependencies NodeJs-ext 

 do you mean i can't have appsignal running locally on my machine ? 

![image](https://user-images.githubusercontent.com/10144036/80209526-87059c00-8632-11ea-8fa6-9f65c9f93df9.png)

thank you

**Comment by xadamy** [comment]
@soufian044 What you're seeing above is actually a bug, so I'm going to put in another ticket for this. However, the agent will still not work on Windows, at least for the forseeable future. As a workaround until I fix the issue so that your project will run locally again, you could wrap `new Appsignal` like this:

```
let appsignal

if (process.platform !== 'win32') {
  appsignal = new Appsignal()
}
```

**Comment by tombruijn** [comment]
Possibly related: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/16410700002923

**Comment by tombruijn** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/mentions/conversations/16410700029272

**Comment by tombruijn** [comment]
We can look at https://neon-bindings.com/ to change how this is installed. Instead of fixing these issues, change how it works.

**Comment by jvanbaarsen** [comment]
Related: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/2788926/conversations/16410700050181

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/16410700116187

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700136844

**Comment by luismiramirez** [comment]
Supported now.

**Comment by tombruijn** [comment]
We don't support it yet. It still won't install for musl systems. I have previously documented this exception on the [supported operating systems page](https://docs.appsignal.com/logging/platforms/integrations/ruby.html) under point 4.
