### ISSUE TITLE
Random checksum validation fails in test suite

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-nodejs#30]
Sometimes a test suite run will fail with the following error:

```
Error: Checksum verification failed
    at Hash.<anonymous> (/home/travis/build/appsignal/appsignal-nodejs/packages/nodejs/scripts/extension.js:56:25)
```

Restarting the job seems to always fix the problem.

**Comment by xadamy** [comment]
This doesn't happen on Semaphore, so closing this issue.

**Comment by thijsc** [comment]
We still see this happening in the agent integration tests.

**Comment by tombruijn** [comment]
This will be continued in https://github.com/appsignal/appsignal-nodejs/issues/505
We still see it happen some of time.
