### ISSUE TITLE
Next.js hot-reload routes are not ignored

### ISSUE THREAD

**Issue by afsanefda** [appsignal/appsignal-nodejs#317]
I have the following code for my nextjs application which has a custom serverjs file:

* server.js - some parts are removed. if something important is missing let me know!

```
/* Appsignal should be initialized before anything else */
const { Appsignal } = require('@appsignal/nodejs');
const { expressErrorHandler , expressMiddleware  } = require('@appsignal/express');

const appsignalssr =  new Appsignal({
  active: true,
  name: process.env.APPSIGNAL_APP_NAME,
  environment: process.env.APPSIGNAL_ENV,
  apiKey: process.env.APPSIGNAL_SSR_KEY,
  log: 'stdout'
});

(async () => {
  await app.prepare();
  const server = express();

if (appsignalssr) {
    /* for setting request route and method in appsignal */
    server.use((req, res, next) => {
      const tracer = appsignalssr.tracer();
      const span = tracer.createSpan({
        namespace: 'web',
        startTime: Date.now()
      });
      span.setName(`${req.method} ${req.url}`);
      span.close();

      next();
    });
  }

  server.use(handler);


  server.get('*', (req, res) => handle(req, res));

  if (appsignalssr) {
    /* should use at the end */
    server.use(expressMiddleware(appsignalssr));
    server.use(expressErrorHandler(appsignalssr));
  }

  server.use((error, req, res, next) => {
    /* eslint-disable */
    if (!error.statusCode) error.statusCode = 500;
    if (!error.name) error.name = 'Express server error!';
    if (!error.message) error.message = 'An Error occurred on express server!';
    /* eslint-enable */

    const tracer = appsignalssr.tracer();
    const span = tracer.createSpan({
      namespace: 'web',
      startTime: Date.now()
    });

    span.addError(error);
    span.close();

    next();
  });

  await server.listen(port);
  console.log(`> Ready on http://localhost:${port}`); // eslint-disable-line no-console
})
```

The problem is when I run this locally I get the route and method but when it is deployed on QA the routes are unknown:

**localhost:** 

<img width="552" alt="Screen Shot 2020-11-05 at 21 42 36" src="https://user-images.githubusercontent.com/37764909/98281602-3217ea80-1fb2-11eb-903c-ca990da870b4.png">

**QA:**

<img width="550" alt="Screen Shot 2020-11-05 at 21 42 25" src="https://user-images.githubusercontent.com/37764909/98281616-347a4480-1fb2-11eb-8152-fc107bf5fe2d.png">

If you need more details let me know!

**Comment by xadamy** [comment]
Hey @afsanefda thanks for the detailed report! 👋 I'm going to need some additional time to look into this locally, but until then, I do notice some interesting things happening here:

- The `/_next/static/webpack/...` URL is a hot-reload endpoint and should be ignored by the integration. So, this is a bug!
- The `GET [unknown route]` that you're seeing in your QA environment is probably something different to the `/_next/static/` URL you're seeing in dev. Are you able to see a path in the performance sample page anywhere?
- It seems like you're duplicating a lot of the work that the integration does for you. For example: where you are doing `span.setName(`${req.method} ${req.url}`);`, the Express integration should do that for you. Did this not work on your machine? If so, one reason for this might be that you're calling `server.use(expressMiddleware(appsignalssr));` _after_ you define your routes, when in fact, it should be _before_ your routes. Try putting the `expressMiddleware()` before your route definitions and see if that makes a difference.

Just FYI, if you need to share things that might not be appropriate for the public to see on Github, then please reach out at support@appsignal.com, and either I or one of my colleagues would be happy to help! 👍

**Comment by afsanefda** [comment]
Thank you.
* for the first item you said it's a bug. Do you mean a bug from our app or the lib?  
* for the second item I filtered paths manually on my serverjs like below and I could be able to see the paths but still I got unknow routes.

```
 if (appsignalssr) {
    /* for setting request route and method in appsignal */
    server.use((req, res, next) => {
      const { pathname } = url.parse(req.url || '/', true);

      /* this is for filtering routes */
      if (!pathname.includes('/_ne/_next/xt/')) {
        const tracer = appsignalssr.tracer();
        const span = tracer.createSpan({
          namespace: 'web',
          startTime: Date.now()
        });
        span.setName(`${req.method} ${pathname}`);
        span.close();
      }

      next();
    });
  }
```

* yes unfortunately in other cases the defaults don't work! 

But the problem with localhost and QA is solved now they are kind of sync now. 
I think I will test it on another next application and if this issue still exists I will let you know or I'll contact support!

**Comment by xadamy** [comment]
@afsanefda 

> for the first item you said it's a bug. Do you mean a bug from our app or the lib?

It's a bug from our library, so not to worry! :) We'll fix this up on our side ASAP.

> for the second item I filtered paths manually on my serverjs like below and I could be able to see the paths but still I got unknow routes.

The correct behaviour here is that hot-reload routes should not appear at all (even as `[unknown route]`), which leads me to think this might be a different issue. 

Seeing `[unknown route]` in your performance table generally means that the Express integration wasn't installed correctly. The Express integration replaces the `[unknown route]` string with whatever the value of `req.route.path` is. However, the order of where you call `server.use(expressMiddleware(appsignalssr));` is important - if you place the middleware before all of the other times you call `server.use(...)`, that should give you correct route names in the UI. If you call `server.use(expressMiddleware(appsignalssr));` after defining a route with `server.use`, you are likely to see `[unknown route]` in the span name.

Also, as an aside, some of the strange behaviour you are seeing could be because you are creating a `Span` here with `tracer.createSpan()`, when in fact you should get the existing `Span` with `tracer.currentSpan()` and modify it. 

```
if (!pathname.includes('/_ne/_next/xt/')) {
        const tracer = appsignalssr.tracer();
        const span = tracer.currentSpan();
        span.setName(`${req.method} ${pathname}`);
        span.close();
}
```

I hope this helps! But if not, feel free to get back to me either here or via support. I will leave this issue open whilst I fix the Webpack hot-reload URL issue mentioned above.
