### ISSUE TITLE
`appsignal-agent` process not ended when `gatsby build` finishes

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#324]
`gatsby build` is a short-lived process so not supported by the agent, but we should still look into why this is happening. 

I added this to the top of `gatsby-node.js`:

```js
const { Appsignal } = require("@appsignal/nodejs");

const appsignal = new Appsignal({
  active: true,
  name: 'Gatsby.js Test',
  // rest of the config here
});
```

**Comment by luismiramirez** [comment]
Closing until a similar one is reported.
