### ISSUE TITLE
`npm run link:npm` doesn't link modules correctly

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-nodejs#327]
Running `npm run link:npm` locally seems to work (i.e. no errors), but doesn't seem to actually link anything. Running `npm link "@appsignal/xxxxxx"` in another project directory doesn't create a symlink to the local copy. I suspect this might be a Lerna issue.

A workaround is to `cd` directly into a directory inside `/packages` and run the `npm link` command there.

**Comment by tombruijn** [comment]
I've not seen this problem with mono anymore. Closing.
