### ISSUE TITLE
Load config from file

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#329]
## The `appsignal.js` file

For Node.js package v3: (use the `opentelemetry` branch as a base)

- [ ] Update installer to write a `appsignal.js` file (or in the `src/` directory if present).
- [ ] Update diagnose tool to read the file if present.
- [ ] Update the docs: https://github.com/appsignal/appsignal-docs/issues/576

**Comment by xadamy** [comment]
With either of these methods, I would want something that allows us to template plugins/intergrations/addons into an array to be loaded by the core library at boot time.

**Comment by tombruijn** [comment]
Related https://github.com/appsignal/appsignal-docs/issues/576

This issue should also be about updating the installer of the integration.
