### ISSUE TITLE
Next.js integration is not compatile with API Routes

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-nodejs#337]
[Next.js API Routes](https://nextjs.org/docs/api-routes/introduction) create a Span correctly but do not update the spans name with the correct route name.

```
[APPSIGNAL]: Next.js debug data { routes: [], matched: undefined, pathname: '/api/hello' }
```

This means that the span name will always be `GET [unknown route]` for an API Route.

**Comment by tombruijn** [comment]
From #381:

> From our testing in #380, @shairyar found that non-root paths aren’t recognized correctly in Next.js applications. I’ve written a [failing test case](https://appsignal.semaphoreci.com/workflows/7f6b3663-d31a-436d-a738-f67eae0b8009?pipeline_id=1e483508-df7e-42c5-bae5-49d072c4e22a) in the [nextjs-non-root-paths](https://github.com/appsignal/appsignal-nodejs/tree/nextjs-non-root-paths) branch. I haven’t yet found a fix to it yet.
