### ISSUE TITLE
Find a replacement for lerna as it seems to be unmaintained

### ISSUE THREAD

**Issue by xadamy** [appsignal/appsignal-nodejs#341]
See:

https://github.com/lerna/lerna/issues/2703
https://github.com/lerna/lerna/issues/2716

This is a shame as we get a lot of value out of using `lerna`, but it's becoming more and more unreliable as time goes on, locks us to `npm@6` and this situation doesn't seem to be changing any time soon.

**Comment by xadamy** [comment]
@tombruijn This was bought to my attention recently as a possible `lerna` alternative: https://github.com/atlassian/changesets

Does this sync up in any way with your thinking around changelog generation and other code quality issues?

**Comment by tombruijn** [comment]
@xadamy That seems quite cool! Is it a full lerna alternative? It's probably written for node, but it would be nice if we could use parts of this, or its ideas, for other integrations as well.

From what I understand it goes like this:

1. A PR author includes `.changeset/my_change.md` file in the PR.
2. When a release is being made, the files are read and a changelog entry is generated.
3. The `.changeset` files are removed, leaving an empty directory for a new release.

They seem to differentiate between patch/minor/major as changelog headings. Which seems fair, as that's what determines what kind of release it is.

In other changelogs I see for example bug fixes, improvements, features, etc., as headings which are useful for humans to read, but subjective in what they are at times.

**Comment by tombruijn** [comment]
https://esbuild.github.io/ could be interesting as well, at least to see what these kinds of tools do.

**Comment by tombruijn** [comment]
I've done a write up on [Basecamp (private link)](https://3.basecamp.com/4738529/buckets/18166704/messages/3513935658)

**Comment by tombruijn** [comment]
Closing in favor of https://github.com/appsignal/appsignal-agent/issues/678
