### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by evenfrost** [appsignal/appsignal-nodejs#343]
Hello,

We're using AppSignal in production and would like to know what changes new releases bring in order to have proper migration (especially when migrating to v1). Thanks!

**Comment by xadamy** [comment]
Hey there @evenfrost 👋 We have a changelog at https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nodejs/CHANGELOG.md, but it starts at `1.0.0` unfortunately.
