### ISSUE TITLE
io-redis integration

### ISSUE THREAD

**Issue by akramali86** [appsignal/appsignal-nodejs#366]
Hi would you possibly consider adding io-redis integration at some point please? https://github.com/luin/ioredis

**Comment by tombruijn** [comment]
Hi @akramali86, we do want to add more integrations like this, but we don't have plans to add a io-redis integration at the moment. We'll keep the issue open so we know which integrations to add. We do have integration with the `redis` package.

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700032439

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700026616

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700086757

**Comment by tombruijn** [comment]
We may be able to pick this up through #391 with the opentelemetry ioredis package.
