### ISSUE TITLE
Diagnose install report location is easily overwritable

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#372]
The diagnose report location is stored in `/tmp/appsignal-install-report.json` which can be easily overwritable by other versions of the appsignal npm package. If there are other apps on the system also using the appsignal npm package they will overwrite this file during the installation of the packages. Only the last install's report will be readable and it might get reported for other apps that it does no longer apply to.

We should look if we can store the report file in the package directory (in `node_modules`) itself, or in some versioned and app path prefixed location.

**Comment by tombruijn** [comment]
We can't store it in the `node_modules/@appsignal/nodejs-ext` dir, because when an optional package fails to install it doesn't persist in the node_modules dir, it gets removed on failure. Probably why it is stored in `/tmp` now.

We can't prefix it with a package version because `npx @appsignal/cli diagnose` doesn't know which package version it was trying to be install. (Also, where does the [cli package](https://www.npmjs.com/package/@appsignal/cli) come from in the repo?)

We could _not_ have the ext package fail with status code 1, and not have it be removed, store the report in there and be able to read it later? As long as the diagnose cli can find that report file later by searching for it in the `node_modules/@appsignal/nodejs-ext` dir?

**Comment by jeffkreeftmeijer** [comment]
I’m not sure about breaking the status code, as that might have effects on the compilation of the app that we’re not foreseeing. Can we use a digest of the current project’s path to create a unique filename to use as the name for the tempfile?

**Comment by tombruijn** [comment]
@jeffkreeftmeijer we could generate a digest based on the app path like so?

```js
#!/usr/bin/node

const { createHash } = require('crypto');
let dir = __dirname

// Whatever I found in the docs to generate a hash
const hash = createHash('sha256');
hash.update(dir);
const hashi = hash.digest('hex');
console.log({ hashi }); // cdb5d15546d89efe58d3772272d3e39bfcc8d1d2435bbaad91d8ccd470413361

// Or basic stripping of dangerous characters
dir = dir.replace(/[\/\\:]/g, "").toLowerCase()
console.log({ dir }) // userstombruijnappsignaltests
```
