### ISSUE TITLE
TypeError: Cannot read property 'dynamicRoutes' of undefined

### ISSUE THREAD

**Issue by feross** [appsignal/appsignal-nodejs#377]
With Next.js 10.0.8, AppSignal throws the following error:

```
Mar 8 11:35:24 AM  TypeError: Cannot read property 'dynamicRoutes' of undefined
    at /opt/render/project/src/node_modules/@appsignal/nextjs/dist/handler.js:16:39
    at Layer.handle [as handle_request] (/opt/render/project/src/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/render/project/src/node_modules/express/lib/router/index.js:317:13)
    at /opt/render/project/src/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/render/project/src/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/render/project/src/node_modules/express/lib/router/index.js:275:10)
```

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700030073

**Comment by jeffkreeftmeijer** [comment]
Hey @feross,

Thanks for reporting this. I’ve been working on a patch to make this work on Next.js 10.x, and we’re reviewing at patch that should solve this issue for you. It’d be great if you could try it out and let us know if it revolves the issue by switching to the `dynamicroutes` branch in your dependencies:

```
"appsignal": "appsignal/appsignal-nodejs#dynamicroutes”
```

Thanks again!

**Comment by jeffkreeftmeijer** [comment]
We had some trouble testing using the git-based dependencies, so we’ve went ahead and released a beta which should resolve this issue. For anyone running into the dynamicRoutes issue described above, please try out `@appsignal/nextjs` version 1.0.9-beta.0 and let us know if that resolves the issue for you:

```
 "@appsignal/nextjs": "1.0.9-beta.0”,
```
