### ISSUE TITLE
Need to split debug and transaction_debug_mode config options

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-nodejs#379]
While testing the nodejs integration I enabled the `debug` config and it seems the log file shows logs that are related to `transaction_debug_mode`. It will be nice to separate the two to be consistent with other integrations.

Related to https://github.com/appsignal/integration-guide/issues/67

**Comment by tombruijn** [comment]
Closing this issue in favor of https://github.com/appsignal/integration-guide/issues/71
