### ISSUE TITLE
Support for NestJS

### ISSUE THREAD

**Issue by thijsc** [appsignal/appsignal-nodejs#382]
Add support for NestJS.

https://nestjs.com/

## To do
- [x] Add instrumentation to the client by default https://github.com/appsignal/appsignal-nodejs/pull/769
  - Only if the instrumentation library is part of the OpenTelemetry core or auto instrumentation package
- [x] Add extractor for OpenTelemetry spans https://github.com/appsignal/appsignal-agent/pull/840
- [x] Add integration test for spans https://github.com/appsignal/appsignal-nodejs/pull/769

**Comment by Karman40** [comment]
Hi, any update for this?

**Comment by tombruijn** [comment]
No update yet. We're working on a bunch of other things for the Node.js integration at the moment.

Related conversation:
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/540709/conversations/16410700077644

**Comment by MrTin** [comment]
What's the status on this? I can't access the Intercom threads above so have no idea what they are about :) I've been using Appsignal extensively as Rails dev but right now I'm working with NestJS, Prisma, and Apollo (GraphQL).

In its current state, it's not really that useful to my team so I might have to look for another solution. I really love Appsignal so would love to see official clients and/or guides to make it work.

We're missing out on some of the most useful features like Slow Queries and Event Timeline that drill down the method chains.

I got it integrated by following this article https://superface.ai/blog/nestjs-with-appsignal and then adapted it to work with Apollo.

**Comment by shairyar** [comment]
Hey @MrTin 

- We do support Apollo. Here are the docs on that: https://docs.appsignal.com/nodejs/integrations/apollo.html
- At the moment, we are working on supporting open telemetry, through that we will be supporting nestjs. We intend to release that in version `3.0` but at the moment there is no timeline on its release. We will update this issue when we release that.
- Prisma is not supported out of the box, so you need to implement [custom instrumentation](https://docs.appsignal.com/nodejs/instrumentation/instrumentation.html), few months back, I was helping another customer with instrumenting Prisma, you can have a look at [this](https://github.com/shairyar/appsignal-prisma/blob/main/app.js#L63-L75) repo to get an idea on how to do the instrumentation.

**Comment by luismiramirez** [comment]
Instrumentation added to the 3.x beta (see linked PRs in description). Span extractors are in progress

**Comment by unflxw** [comment]
Hello, NestJS users! @MrTin @Karman40

We have just released a beta of the AppSignal for Node.js instrumentation that includes [NestJS support](https://docs.appsignal.com/nodejs/3.x/integrations/nestjs.html). It also includes other niceties from previous betas, such as Prisma support.

To install it, [follow the instructions on our installation guide](https://docs.appsignal.com/nodejs/3.x/installation). If you're already using AppSignal, this is a beta for the new major version of our AppSignal for Node.js integration, so there will be breaking changes. You should find [the migration guide](https://docs.appsignal.com/nodejs/3.x/migration-guide.html) useful.

Let us know what you think! If you run into any issues, our support team will be happy to help, be it here, through the AppSignal application, or at support@appsignal.com.
