### ISSUE TITLE
Track test code coverage

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-nodejs#388]
Set up a way to track code coverage. We're not aiming for 100% coverage necessarily, but we do want to know what things are currently untested.

- [ ] Set up a way to learn and keep track of code coverage
- [ ] Determine which packages need more coverage, create new issue for coverage targets for them

Part of https://github.com/appsignal/integration-guide/issues/59

**Comment by tombruijn** [comment]
I've updated this issue to focus only on the code coverage setup, so that the other issue https://github.com/appsignal/appsignal-nodejs/issues/605 can focus on what things are untested.
