### ISSUE TITLE
Diagnose command improvements

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-nodejs#390]
We’ll update the diagnose command to be feature complete, compared to the Ruby integration. We’ll start by documenting what a complete implementation is in the integrations handbook.

## To do

- [x] Feature completeness check against other integrations
- [x] https://github.com/appsignal/appsignal-nodejs/issues/375
- [x] https://github.com/appsignal/appsignal-nodejs/issues/371
- [x] https://github.com/appsignal/appsignal-nodejs/issues/372

**Comment by tombruijn** [comment]
@jeffkreeftmeijer is this done now (all items are checked off) or are there more differences in the diagnose report we need to fix?

**Comment by jeffkreeftmeijer** [comment]
There’s a [difference in printed configuration options](https://github.com/appsignal/diagnose_tests/blob/main/spec/diagnose_spec.rb#L348-L381), which we can fix later. I’d say this project is done with the Node.js diagnose tests running on CI, giving us a solid base to work from from now on.
