### ISSUE TITLE
OpenTelemetry research

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-nodejs#391]
We’ll research becoming a consumer of OpenTelemetry metrics from other libraries, and will determine if that’s an approach we’d like to take to open up support for existing libraries. We’ll then estimate and plan the project.

See if we can implement this before adding support for things like [MySQL](https://github.com/appsignal/appsignal-nodejs/issues/216) so we don't have to implement it several times.

**Comment by 2color** [comment]
This would be great! Looking forward to seeing progress on this.

**Comment by tombruijn** [comment]
I'm continuing this in https://github.com/appsignal/integration-guide/issues/47 (private issue).
