### ISSUE TITLE
Application doesn't shutdown on SIGINT

### ISSUE THREAD

**Issue by 2color** [appsignal/appsignal-nodejs#398]
I recently added the Appsignal Node.js agent to an application and noticed that the application doesn't shut down anymore on SIGINT and SIGTERM. 

I tried adding the following:

```js
process.on('SIGINT', () => {
    appsignal.stop()
  })
  process.on('SIGTERM', () => {
    appsignal.stop()
  })
```

But the application still doesn't gracefully shut down. 

Am I missing something?

**Comment by shairyar** [comment]
Hey @2color since you sent this via email as well so I am going to close this and get back to you via email.

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700039796

**Comment by hjvedvik** [comment]
@shairyar I'm experiencing the same issue. Would you mind posting the solution here too? :)

**Comment by shairyar** [comment]
@hjvedvik Daniel ran into multiple issues and I created this [PR](https://github.com/2color/fastify-graphql-nexus-prisma/pull/3) to help him out, I have not heard back if he is still having the problem. Could you please write to us at support@appsignal.com with your case so we can look into it?
