### ISSUE TITLE
MongoDB integration

### ISSUE THREAD

**Issue by adamyeats** [appsignal/appsignal-nodejs#44]
https://github.com/Automattic/mongoose

**Comment by xadamy** [comment]
Currently blocked as work needs to be carried out in the agent. See https://github.com/appsignal/appsignal-agent/issues/563 (AS team only).

**Comment by rmachielse** [comment]
We would be very happy to see this 🙏😄

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700024339

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700060256

**Comment by luismiramirez** [comment]
Supported in v3
