### ISSUE TITLE
Merge extension package into nodejs package

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#471]
## Background

The extension installation and install report from the `@appsignal/nodejs-ext` package are outside of the core package `@appsignal/nodejs`. The `nodejs-ext` extension package is an [optional dependency](https://github.com/appsignal/appsignal-nodejs/blob/ea685296957fdbd61dd13e168a5adbb64797d243/packages/nodejs/package.json#L18-L20) of the core package.

When the extension installation fails in the `nodejs-ext` package, npm will delete the failed package directory. Which is why we have to check if the module was loaded or not in the [`ExtensionWrapper`](https://github.com/appsignal/appsignal-nodejs/blob/ea685296957fdbd61dd13e168a5adbb64797d243/packages/nodejs/src/extension_wrapper.ts#L5-L18)

While working on issue #357 to merge the two listed files, I noticed that we can't rely on `nodejs-ext` package to be present to get the version from as it may not be loaded if something fails during installation. So, to know the current agent version at all times in the `nodejs` package, we copy it to another file in the `nodejs` package files using this [version file script](https://github.com/appsignal/appsignal-nodejs/blob/ea685296957fdbd61dd13e168a5adbb64797d243/packages/nodejs/scripts/create-versionfile.js).
 
## The problem

- Keeping the extension-related operations in a separated package from the core one doesn't make any sense as `@appsignal/nodejs` will not work without the extension, and no other package is directly dependent on the extension.
- An unsuccessful installation should not panic in any case making the dependency installation fail for the customer's application or preventing a package from being installed. Our other integrations don't work this way either.
- The diagnose tool has to fetch the extension install report from the host's global `/tmp` dir, which may not include the install report if an intermediate build machine was used and the app was copied over to the production host.

## The proposal

- [x] Move the extension-related operations into `@appsignal/nodejs` package
- [x] Prevent the extension installation from panicking when something goes wrong
- [x] Get version values from the extension constants
- [x] Remove `create-versionfile.js` script from `@appsignal/nodejs`
- [x] Do manual testing on extension installation failures, to check
    - That the `npm install` process __does not__ exit with a failure exit code.
    - That the `appsignal/nodejs` package __is not__ removed from the file system on failure.
- [ ] Do manual testing on Windows to also verify the above tests

**Comment by luismiramirez** [comment]
Could you add your feedback about this, please?

@jeffkreeftmeijer, @unflxw, @thijsc

No feedback will be taken as an approve

**Comment by unflxw** [comment]
Looks good to me 👍 Some concerns were raised on [the Slack conversation about this](https://appsignal.slack.com/archives/CNPP953E2/p1635411020005200). As long as failure scenarios still work well when the packages are merged (diagnose still possible), this change should be a good thing.

**Comment by tombruijn** [comment]
We're moving forward with this. I'm removing the discuss label.

**Comment by thijsc** [comment]
Sorry for the late reply on this.

This separate package actually fulfills an important purpose: It allows the extension to fail installing without breaking the user's `npm install`. If somebody is running on Windows they still need to be able to install the core package. In other integrations we can fail and still have the bundle/hex install succeed.

The only way we could get this scenario to work in Node is using an optional package. We tried, but could not find any other working way. If that's still true that'd be a reason to keep the separate package.

**Comment by thijsc** [comment]
Some context: This was because of a limitation in `node-gyp`. Maybe this limitation does not exist in the newer cmake thing, maybe we should pick up #386 before this one.

**Comment by tombruijn** [comment]
@thijsc I don't think this is true anymore. Previously the `extension.js` file only prepared everything for installation, only to then hand it off to the `node-gyp` program. If that program failed the package failed to install and npm would remove it from the file system.

With the changes in #409 the `extension.js` script now wraps the `node-gyp` program and manually returns a failure exit status if `node-gyp` failed. This was done to record in the diagnose report, if and why the installation failed.

We could make the `extension.js` script not return an failure exit status now. That way the `npm install` process doesn't fail if the extension installation failed.

- Changes to `extension.js` to wrap `node-gyp`: https://github.com/appsignal/appsignal-nodejs/commit/1b54698178414559878ea1bba51408eac03600e3#diff-0672a35b092a18a7c390dc3db97e675ff4c488d9a7fa95332594e92a3803b66b
- Where we called `node-gyp` in `package.json`'s `npm run install` script previously: https://github.com/appsignal/appsignal-nodejs/commit/1b54698178414559878ea1bba51408eac03600e3#diff-a6f452505892c1f28f41198fc64095fb973b72396ea5cac9fd5527689fd4e6a8
- Location we return exit code 1 manually on failure: https://github.com/appsignal/appsignal-nodejs/blob/df4163fc10e972934ff62fe7a1ac6cbcd0416335/packages/nodejs-ext/scripts/extension.js#L252

**Comment by thijsc** [comment]
Ok great! Then this is not a concern anymore. Would be good to test installing on windows after we do this change to make sure.

**Comment by tombruijn** [comment]
Ok! I added extra to do items for the new setup for testing on install failure and testing on Windows to confirm it works like we expect.
