### ISSUE TITLE
Diagnose reports include an undefined config key

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#472]
Diagnose reports sent from the Node.js integration include a config option key named `undefined`. This shouldn't happen.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/282402/139431768-9d37cf99-3998-4d7b-8c93-4e4c6f35ada2.png">

It looks like it's value is similar to that of the `log_path` config option, except that it also includes the `appsignal.log` file path, which it shouldn't.

Where does this config option value come from? And can we remove it from the diagnose report?

This could be possibly partially resolved by this issue: https://github.com/appsignal/diagnose_tests/issues/21
But it's still strange an `undefined` key is included in the config object. I created this issue to explore that we check if the keys we set are actual String values that are config keys, and not the value `undefined`.

Example diagnose report (on staging): https://staging.lol/admin/diagnose_reports/diag48db106d49eb0857a8a1
The config section from the report:

```json
{
  "config": {
    "options": {
      "debug": false,
      "log": "file",
      "log_path": "/tmp",
      "ca_file_path": "/Users/tombruijn/appsignal/nodejs/packages/nodejs/cert/cacert.pem",
      "endpoint": "https://push.appsignal.com",
      "env": "development",
      "push_api_key": "[FILTERED]",
      "active": true,
      "undefined": "/tmp/appsignal.log"
    },
    "sources": {
    }
  },
}
```

**Comment by luismiramirez** [comment]
Working on this from: https://github.com/appsignal/diagnose_tests/issues/21
