### ISSUE TITLE
The requestHeaders config option is not implemented

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#487]
## The problem

The `requestHeaders` config option is an _allowlist_ of the headers the users want to see in AppSignal for their requests.

The option is not implemented. It is present in the [config maps](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nodejs/src/config/configmap.ts), but it doesn't have default values nor is checked in the diagnose tests.

## The proposal

- [ ] Add a default value for the new option and make it user-configurable
- [ ] Send the headers with the key `environment` in the spans sample data after filtering them using the config option
- [ ] Update the docs to let the users know about the new option and how it works

**Comment by tombruijn** [comment]
Our Ruby defaults can be found here: https://github.com/appsignal/appsignal-ruby/blob/c07a1322e4c30d1077a0ce994ced849d1eaa57d0/lib/appsignal/config.rb#L23-L29
GDPR docs about this here: https://docs.appsignal.com/appsignal/gdpr.html
