### ISSUE TITLE
The logFilePath function should check if user specified config is writable

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#492]
The Node.js integration should verify that the `logPath` option configured by the user points to a writable path.

If the path is not writable, it should fall back on the system `/tmp` dir.

If we do not do this, and the path points to a path that does not exist or is not writable, it will cause problems with logging: we can't log to a file and the agent cannot start (or it will fall back on the tmp path anyway).

See also #490 for other changes to `logFilePath`

## To do

- [ ] Add check to the `logFilePath` function to verify the path is writable.
- [ ] If the path is not writable, fall back on the system's `/tmp` dir. Please use a cross platform helper to determine what is the host's system "tmp" dir. It's probably this helper `os.tmpdir()`.

**Comment by tombruijn** [comment]
Oh actually we already specify the global tmp dir as the default here as well:

https://github.com/appsignal/appsignal-nodejs/blob/3e78323af95527b34ae594ea5ca82f8e12aec295/packages/nodejs/src/config.ts#L81

But that should use that `os.tmpdir()` helper too.

**Comment by tombruijn** [comment]
I had a look at `os.tmpdir()` behavior.
We want it to point to `/tmp` on macOS and Linux.

```js
const os = require("os")
// macOS
> os.tmpdir()
'/var/folders/n1/hhn53f_5155868x3pkg16wdh0000gn/T'
// Linux
> os.tmpdir()
'/tmp'
```

So `os.tmpdir` may not be the way to go.

**Comment by luismiramirez** [comment]
`os.tmpdir()` first takes a look at `TMPDIR`, `TMP`, and `TEMP` environment variables before falling back to `/tmp`. We can use it for [Windows](https://github.com/nodejs/node/blob/master/lib/os.js#L37) if we want to support it, and then hardcode `/tmp` for Linux and macOS
https://github.com/nodejs/node/blob/master/lib/os.js#L173-L192

```js
function tmpdir() {
  var path;
  if (isWindows) {
    path = process.env.TEMP ||
           process.env.TMP ||
           (process.env.SystemRoot || process.env.windir) + '\\temp';
    if (path.length > 1 && StringPrototypeEndsWith(path, '\\') &&
        !StringPrototypeEndsWith(path, ':\\'))
      path = StringPrototypeSlice(path, 0, -1);
  } else {
    path = safeGetenv('TMPDIR') ||
           safeGetenv('TMP') ||
           safeGetenv('TEMP') ||
           '/tmp';
    if (path.length > 1 && StringPrototypeEndsWith(path, '/'))
      path = StringPrototypeSlice(path, 0, -1);
  }

  return path;
}
```

**Comment by tombruijn** [comment]
> We can use it for Windows if we want to support it, and then hardcode /tmp for Linux and macOS

Sounds good.
