### ISSUE TITLE
Store configuration in global object

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#493]
## The background

Due to the development of:

- https://github.com/appsignal/integration-guide/issues/31
- https://github.com/appsignal/integration-guide/issues/80
- https://github.com/appsignal/appsignal-nodejs/issues/486

Entities like `Span` need to access AppSignal's configuration to know which data keys to filter.

## The problem

Accessing the configuration from everywhere within the integration is not possible right now as the configuration is only accessible when you have the client available, and `Span` doesn't.

Ruby and Elixir integrations already have a solution to make the config available everywhere in the integration.

## The proposal

- [x] Store AppSignal's configuration under the property `__APPSIGNAL__` when [initializing](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nodejs/src/config.ts#L20-L32)
- [ ] <del> Make the configuration readable to avoid calling the global object from everywhere</del>

**Comment by tombruijn** [comment]
For now I would only make it possible for us to access it from the global object. You don't need to update the integrations, like the express one, to not accept the config/client argument anymore. We'll do that later.
