### ISSUE TITLE
Make client accessible from global object

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#503]
## The background

The client instance needs to be moved between packages to access the tracer, which gives access to the error tracking helpers, the root, and the current span.

Currently, `Client` and `Tracer` instances are moved into the different integrations internals:

- [Express](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/express/src/middleware/index.ts#L1)
- [Koa](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/koa/src/patches/index.ts#L7)
- [Apollo](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/apollo-server/src/index.ts#L1)
- [NextJS](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nextjs/src/handler.ts#L2)
- [Redis](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nodejs/src/instrumentation/redis/index.ts#L1)
- [PG](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nextjs/src/handler.ts#L2)
- [HTTP](https://github.com/appsignal/appsignal-nodejs/tree/main/packages/nodejs/src/instrumentation/http/lifecycle)

The client is now stored in global object (#493).

## The proposal

- [x] Create a helper, like a class function for `Client` that provides clean access to the stored client (https://github.com/appsignal/appsignal-nodejs/pull/534)
- [ ] Change the integrations to access the `Client` and the `Tracer` from global object instead of passing them to the functions
  - [ ] Express
  - [ ] Koa
  - [ ] Apollo
  - [ ] NextJS
  - [ ] Redis
  - [ ] PG
  - [ ] HTTP

## Caveats

- This may change how the framework integrations are initialized from customer's applications, so don't consider any of these changes part of **patch** or **minor** release.
- Avoid opening a big PR for the whole thing. One for each integration should be OK

**Comment by tombruijn** [comment]
Users won't necessarily have to change anything to make it work at the moment? They should remove the client being given to the express middleware, for example, but it would work if they pass it in anyway. So it's not necessarily a breaking change until we change how the config is initialized.

Eventually I would hope we can make some kind of function to set the global config, rather than set it when the configuration class gets initialized. For example:

```js
Appsignal.configure({ active: true })

function configure(options) {
  const config = new Appsignal(options)
  storeInGlobal(config)
}
```

**Comment by luismiramirez** [comment]
That way of initializing Appsignal is exactly what I was thinking about 👌🏼 

> But we can do this in small steps and only have the last step (changing how the config is initialized) be the major change.

Agree

**Comment by luismiramirez** [comment]
Non relevant with the new v3.0
