### ISSUE TITLE
The httpProxy option isn't used by the diagnose transmitter or Push API key validator

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#518]
Part of https://github.com/appsignal/integration-guide/pull/105

The `httpProxy` config option is currently only configured to be used by the agent, but the diagnose report transmitter and Push API key validator do not use this config option's value.

We're running into issues using the http/https libraries in Node.js directly do to missing documentation and missing safety checks. Implementing [proxy support](https://github.com/appsignal/appsignal-nodejs/issues/518) has been a big chore so far that we haven't been able to figure out.

We need this http(s) capability for the following scenarios:

- Download the agent and extension in the installer
- Validate the Push API key on install and diagnose
- Transmit the diagnose report

## Alternative libraries

There's a popular library axios that we can use instead that has more checks and proper proxy support.

We prefer not to add additional dependencies unless absolutely necessary. We've done something similar in Elixir; we use hackney as an HTTP library. Ideally though, we find a way to use the standard library for these types of things.

## Research

- [ ] Research if we can improve our usage of the http/https libraries
- [ ] If not, research axios, or other light weight alternatives. Write up a comparison.
- [ ] Decide with the team if we want to use an extra library for http/https.

## To do

- [ ] Update the [diagnose report transmitter](https://github.com/appsignal/appsignal-nodejs/blob/1a2bef0a710ff9b40129fc90aa25bd2f4230f400/packages/nodejs/src/diagnose.ts#L252) to use the config option value.
- [ ] Update the [Push API key validator](https://github.com/appsignal/appsignal-nodejs/blob/1a2bef0a710ff9b40129fc90aa25bd2f4230f400/packages/nodejs/src/diagnose.ts#L124) to use the config option value.
- [x] Check the difference between the two transmitters and see if they can't be merged into one reusable transmitter. Related #517.

**Comment by luismiramirez** [comment]
After working on this one for a while, we decided not to continue as it requires more work than expected.

Node.js native proxy connection support is poorly documented, not to say not documented at all. The best I could find was this [StackOverflow answer](https://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client), and it only works for HTTP. The support is even worse to connect to an HTTPS through a proxy.

We need to spend a bit of research on this one and make a decision as a team:
- Keep fighting with `http` and `https` modules
- Use an external package that provides proxy support out of the box

**Comment by tombruijn** [comment]
As discussed, we can also hold off on working on this for a while. No one has asked for it yet, so I see no rush to put it in if it's a lot of work right now

**Comment by unflxw** [comment]
Regarding axios, here's how they implement proxy support themselves: https://github.com/axios/axios/blob/73e3bdb8835ba942096b662e9441f1d85ce4d484/lib/adapters/http.js#L27-L44
