### ISSUE TITLE
Support Express route normalization

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#52]
Report routes as

`GET /posts/:id/comments/:comment_id`

Rather than the actual path:

`GET /posts/123/comments/389033`

Reported in: https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/540709/conversations/25943457815

**Comment by matsimitsu** [comment]
Related: https://github.com/appsignal/appsignal-server/issues/5592

**Comment by xadamy** [comment]
Re-opening as we have implemented a temporary solution for getting the `req.route.path` from `express`. We'll need something more permanent that plays nice with the core `http` integration.

**Comment by xadamy** [comment]
Fixed in `0.3.0`, we can now get the path from `req.route.path` successfully.
