### ISSUE TITLE
Use transmitter class in extension installer

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#532]
The node.js integration's extension installer now uses the https library directly. We've made an abstraction for this in PR #531, we should use that instead. This way it also supports the cacert file and other config options.

~🚨 This is blocked on merging the extension package into the main package: https://github.com/appsignal/appsignal-nodejs/issues/471~
~Because the extension package can't load the transmitter from the main package without creating a circular dependency chain. And we don't want to duplicate it.~

## To do

- [ ] Use the transmitter class in the `extension.js` script.
    - https://github.com/appsignal/appsignal-nodejs/blob/434599b1496cc1570713465610f794b5118f1733/packages/nodejs/scripts/extension/extension.js#L51-L65

**Comment by tombruijn** [comment]
Moving directly to "to do", as we've already discussed this with the team in the call.

**Comment by unflxw** [comment]
PR #600 also related to this task.
