### ISSUE TITLE
Heap statistics should be displayed for every host

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-nodejs#540]
We track the metrics for heap statistics but don't separate those from different apps on different hosts. The last host that pushes metrics for a certain minute overwrites all the other collected metrics and this makes it not possible to know from which app the metrics in the graph are coming from.

This is the file where we collect the metrics, but no tags are being added: https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nodejs/src/probes/v8/index.ts

## To do

- [x] Add a tag with the hostname to the linked metrics - https://github.com/appsignal/appsignal-nodejs/pull/543
- [x] Update the magic dashboard config - https://github.com/appsignal/public_config/pull/36
- [ ] Update the magic dashboard for existing dashboards.

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700082948

**Comment by tombruijn** [comment]
@unflxw I think the magic dashboard was updated in https://github.com/appsignal/public_config/pull/36? I'll close the issue then.
I think @thijsc was working on (auto) updating the existing magic dashboards in a different issue.
