### ISSUE TITLE
Revisit printing extension load error on Extension start

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#555]
At the moment we print the extension load error when the extension is started: https://github.com/appsignal/appsignal-nodejs/blob/58f1ae0b5ed62f9a92c736515a2efb2b5d2859da/packages/nodejs/src/extension.ts#L22-L31

In other integrations we do this on load: https://github.com/appsignal/appsignal-ruby/blob/ef2982fd7d1760f8062a20fa15a46131a0745cd2/lib/appsignal/extension.rb#L13-L19

We should check why this is done on start in the Node.js integration and if we can't do this on load as well.

If it's a problem with not supported Operating Systems printing this message every time on start, we can also think of a way to not always show this. Like an env var to disable to message or track if a user has ignored it somehow with a local config option.

**Comment by tombruijn** [comment]
I'm probably in favor of printing the error on load, rather than on extension start. As we've seen in issue https://github.com/appsignal/appsignal-nodejs/issues/556, we also call extension functions when the extension function is not started. If we and the user are not alerted to the fact the extension has not loaded properly, we may approach this issue with the wrong assumption.

To allow users to hide the error we can add an environmental variable like `APPSIGNAL_SILENCE_EXTENSION_LOAD_ERROR`.

At all times this warning must be logged to the AppSignal logger (file or stdout depending on the `log` option).

**Comment by tombruijn** [comment]
Putting this in the to do list because the currently shipped implementation in nodejs package 2.3.0 doesn't show the load error if the extension isn't started.

**Comment by unflxw** [comment]
I want to make sure that I understand this task. What do we mean by "on load" when talking about "printing the error on load, rather than on extension start"? Is it that we want to emit these console warnings when the extension module is required/imported, rather than when `extension.start()` is called?

> If it's a problem with not supported Operating Systems printing this message every time on start, we can also think of a way to not always show this.

I'd wait for someone to ask for that. I don't think users will be annoyed enough by the message to go through the effort of setting an environment variable to suppress it.
