### ISSUE TITLE
Instrumentation plugins should not be initialised when `active` is set to false

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#559]
A user reported ([Intercom conversation](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700080008#part_id=comment-16410700080008-12298450414)) that the redis instrumentation was failing to initialise and bringing down the whole integration with it, **even when `active` is set to false.**

There is no need to do the whole require-in-the-middle and set up a wrapper that calls instrumentation when the integration isn't active.

**Comment by tombruijn** [comment]
We have a similar report about the same error here: https://github.com/appsignal/support/issues/184

**Comment by tombruijn** [comment]
> There is no need to do the whole require-in-the-middle and set up a wrapper that calls instrumentation when the integration isn't active.

I suppose we can listen to the config option `active` value here in this case, see also https://github.com/appsignal/integration-guide/issues/126 if we want to implement that behavior.

Currently only `ignoreInstrumentation: ["redis"]` allow users to disable it, an undocumented config option. See also https://github.com/appsignal/appsignal-nodejs/issues/519

**Comment by tombruijn** [comment]
Closing this in favor of https://github.com/appsignal/integration-guide/issues/126
