### ISSUE TITLE
Dependabot is not picking up our changelog

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#564]
Quoting a user report ([Basecamp link](https://3.basecamp.com/4738529/buckets/18166704/messages/4549264665)):

> Another note I have: your releases don't have (public) changes:
I just got this: 
Dependabot: Bump @appsignal/express from 1.0.18 to 1.0.23 #507  
> Most times this shows changes or commits, but not with your package. That makes it harder to see what's changed (and the impact).

I've tried to look into how Dependabot finds the changelog to add some potential implementation pointers to this issue, but all I could find is ["it depends"](https://github.community/t/how-does-dependabot-get-release-notes/160952/3) and ["not from npm"](https://stackoverflow.com/questions/34971504/how-do-i-see-the-release-notes-for-an-npm-package-before-i-upgrade) -- so the first step is probably figuring this out.

**Comment by tombruijn** [comment]
I just added the package details to the npm packages in PR #563. Hopefully that gets picked up and it gets fixed automatically.

Previously we had a similar issue with Depfu for the Ruby gem, when we renamed the `master` branch to the `main` branch, which we had to reach to manually update to the new location. Maybe it's the same for Dependabot. We should reach out and ask what is going wrong.

**Comment by tombruijn** [comment]
We can ask the user if the update in the last release helped. If not, send an email to GitHub support.

**Comment by tombruijn** [comment]
I've contacted the user: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700087048?simulator=false

**Comment by tombruijn** [comment]
I made a test repo with an outdated `@appsignal/nodejs` package and told Dependabot to update it. This is the PR it made: https://github.com/tombruijn/dependabot-changelog-test/pull/1

The changelog appears to be picked up okay. Closing the issue.

![image](https://user-images.githubusercontent.com/282402/166888059-453f3718-f48d-4cea-881e-ec219ee5eb84.png)
