### ISSUE TITLE
Using ESLint for linting

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#604]
We currently use prettier to format our code, but we don't really "lint" our code base. Let's set up ESLint in this project as well. We need to use a [TypeScript compatible plugin](https://typescript-eslint.io/) probably. I also know there's a package like [prettier-eslint](https://www.npmjs.com/package/prettier-eslint). It's confusing to me. I don't think we necessarily want to remove prettier in favor of ESLint, even though ESLint also does some formatting, they just shouldn't disagree with each other.

## To do

- [x] Set up ESLint with TypeScript in a compatible way with prettier.
- [ ] When we are happy with the result, create a similar issue for the JavaScript repo
- [ ] Update handbook (issue) with new state: https://github.com/appsignal/handbook/issues/58. Leave a comment or update the issue description.

**Comment by tombruijn** [comment]
@unflxw are you working on adding ESLint to the JavaScript repo as well? Or can we create a new issue for that?

**Comment by unflxw** [comment]
@tombruijn Not actively working on it at the moment, but I do consider it part of this issue and want to get around to it. Now that we've figured out for Node, it hopefully won't be too hard to get it working on the JavaScript repo.

**Comment by tombruijn** [comment]
Ok. Then I'm moving it back to "To do".
