### ISSUE TITLE
Refactor Transmitter into an unsurprising HTTP client

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#615]
[As discussed](https://github.com/appsignal/appsignal-nodejs/pull/603#discussion_r803529231) in #603, I think we should consider refactoring the `Transmitter.request` method into an unsurprising HTTP client: that is, one with an ergonomic API, where you provide an object describing an HTTP request you'd like to do, and you get a promise for a reasonable representation of the HTTP response you'd like to receive. One where the caller doesn't have to [care about the details of event-based HTTP request handling in Node](https://github.com/appsignal/appsignal-nodejs/pull/603/files#diff-0a3e2e7e0fed3f64c16b71cbc1cd8dcc8731cc11e73f3d826a3412450d41c310R57-R62), and without hardcoding into it [the specific needs of some of our endpoints regarding query parameters](https://github.com/appsignal/appsignal-nodejs/pull/603/files#diff-0a3e2e7e0fed3f64c16b71cbc1cd8dcc8731cc11e73f3d826a3412450d41c310R52), or our specific expectations regarding [what constitutes a successful request](https://github.com/appsignal/appsignal-nodejs/pull/603/files#diff-0a3e2e7e0fed3f64c16b71cbc1cd8dcc8731cc11e73f3d826a3412450d41c310R34-R35) or [how to process the response as a JSON](https://github.com/appsignal/appsignal-nodejs/pull/603/files#diff-0a3e2e7e0fed3f64c16b71cbc1cd8dcc8731cc11e73f3d826a3412450d41c310R65-R68).

The new `.request` method is halfway there, but:
- it expects you to handle the events on the response yourself, as a way to allow for the response to be treated as a stream (`.downloadStream`) or as a JSON (`.transmit`). This could be better handled by an argument in the request object that specifies the expectations for the response, like `response: 'stream'` or `response: 'text'`.
- it does not return a promise, as you have to process the events from the response yourself, and it is up to the caller to decide, based on the outcome of those events, if a promise is resolved or rejected.

If these shortcomings were resolved, the `.transmit` and `.downloadStream` methods could be removed entirely, and their usages could be replaced by plain calls to `.request`, moving the "unusual" stuff that they do where it makes sense to do so. Here's a made-up API of what that could look like at the usage point:

```
const diagnoseReportResponse = await transmitter.request({
  method: 'POST',
  url: 'https://...',
  body: JSON.stringify(diagnose),
  params: { api_key: this.#config['push_api_key'], ... }
  // response: 'text' // this should probably be the default value
})

if (diagnoseReportResponse.statusCode == 200) {
  // do things with JSON.parse(diagnoseReportResponse.text)
}
```

In the example above, the query parameters for the request are moved here, where they are contextually relevant, instead of having them set for all requests in the `.transmit` wrapper. The API for the transmitter no longer expects some parts of the request to be specified in the initialiser for the class and others in the method invocation. The method returns a promise that resolves to an object representing the response.

If we still wanted to have convenience wrappers for these requests in the transmitter, we could now have those wrappers be meaningful for each request (`.sendDiagnoseReport(diagnose)`, `.validatePushApiKey(push_api_key)`), instead of wrappers with generic-sounding names like `.transmit` that actually do very specific things.

The only things we'll want to keep hardcoded in the transmitter are those who would remain true for any HTTP requests done via our application, that is, configuration-based CA overrides and, in the future, HTTP proxy settings.

Thoughts? This is an (admittedly opinionated) proposal. Perhaps we don't need this now, or ever. Perhaps we want to use Axios and get an ergonomic HTTP requests API for free, and do a refactor around that instead.

**Comment by tombruijn** [comment]
This would be a nice refactor, but not very necessary at the moment. We can come back to it later if we want.
How much time do you think it would take if you pick it some time soon?

**Comment by luismiramirez** [comment]
@unflxw Is this applicable to v3?

**Comment by unflxw** [comment]
I think we can safely bin this issue.
