### ISSUE TITLE
Fix `setSampleData` TypeScript signature

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#624]
As mentioned in #622, [we use the `@ts-ignore` annotation to ignore a signature mismatch on the Express middleware](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/express/src/middleware/index.ts#L51). This is not actually any sort of "parse error", just a good old type mismatch: we're passing an arbitrarily-nested object to a function whose declared signature says it accepts objects with one or two levels of nesting. More specifically:

```typescript
// `query` is a `ParsedQs` from the `qs` library, which is defined as:
interface ParsedQs { [key: string]: undefined | string | string[] | ParsedQs | ParsedQs[] }
// see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a2c5035e657b5b7a20ac14377e48344c3e00bd5/types/qs/index.d.ts#L57
// this is a recursive type, meaning ParsedQs is an arbitrarily-nested object

// we pass it to `span.setSampleData`, which is defined as:
public function setSampleData(
  key: string,
  data:
    | Array<
        HashMapValue | Array<HashMapValue> | HashMap<HashMapValue> | undefined
      >
    | HashMap<
        HashMapValue | Array<HashMapValue> | HashMap<HashMapValue> | undefined
      >
): this
// see https://github.com/appsignal/appsignal-nodejs/blob/ae012e70f6aa001f0e79ccf7aab1d23506e9e03d/packages/nodejs/src/interfaces/span.ts#L90-L99
// which is not recursive, it only allows one or two levels of nesting

// therefore, the following fails:
span.setSampleData("params", { ...params, ...query })
```

We should probably address this by fixing the type signature on `span.setSampleData`, as it should accept recursive types. Afterwards, we should remove the `@ts-ignore` annotation and re-enable the ESLint rule that disallows its use.

**Comment by tombruijn** [comment]
We should allow arbitrary nesting for keys like `params` and `custom_data`, but no the others.
