### ISSUE TITLE
Use Semaphore artifacts instead of the cache

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#631]
Currently, our build system uses the Semaphore cache system to pass the build artifact from the Build stage to the testing stages. [The Semaphore artifact system would be a better fit for this use case.](https://docs.semaphoreci.com/essentials/artifacts/#workflow-artifacts)

**Comment by tombruijn** [comment]
Added note that if we don't it can break again silently and we won't know until we clear the cache.
