### ISSUE TITLE
Fix Next.js test example failure on Node <= 14

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#632]
[See sample failed build from the `main` branch on Semaphore.](https://appsignal.semaphoreci.com/workflows/eca33c5f-22f8-47ff-8355-9fe64bdc336e?pipeline_id=709d6e85-a603-4c64-abcd-111cf1575d56)

This was uncovered after cleaning the caches and fixing the build step for Node <= 14; see #628, #629 and [this Slack conversation](https://appsignal.slack.com/archives/CNPP953E2/p1648126339853399). This failure may or may not be related to the switch to NPM version 7 for these Node versions, implemented in #629.

**Comment by tombruijn** [comment]
If it takes too much work to fix right now. I would first disable the test, mark it pending, and get back to it after issue #631 again.
