### ISSUE TITLE
npm install failing on Windows 10

### ISSUE THREAD

**Issue by ragibsm** [appsignal/appsignal-nodejs#646]
When I try to install @appsignal/nodejs and @appsignal/express I get the following error:

npm ERR! code 1
npm ERR! path C:\Projects\test-project\node_modules\@appsignal\nodejs
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c if test -d src; then npm run build; fi        
npm ERR! -d was unexpected at this time.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-04-14T08_30_02_968Z-debug-0.log

Node version: v16.14.2
npm version: v8.6.0

**Comment by tombruijn** [comment]
Thanks for the report @ragibsm! I have made a fix in PR #647.

**Comment by ragibsm** [comment]
Thanks @tombruijn! Is there any timeline when the PR could be merged?

**Comment by ragibsm** [comment]
@tombruijn Any update on this? Thanks
