### ISSUE TITLE
Express integration logs nothing?

### ISSUE THREAD

**Issue by matiasgarcia** [appsignal/appsignal-nodejs#648]
We are using Appsignal in our ExpressJS application and we noticed that nothing useful is logged at all:
We are unsure if this is a bug, a configuration issue, or something else.

For example:
```
import { appsignal } from './appsignal';
import { expressMiddleware, expressErrorHandler } from '@appsignal/express';

import express, { NextFunction, Request, Response } from 'express';
import pino from 'pino-http';
import { logger } from './config/logger';
import { client } from './lib/client';
import { RoutesV2, PublicRoutesV2 } from './routes';
import { renderUnauthorized } from './routes/api/raw_helpers';

const app = express();

app.disable('x-powered-by');
app.use(pino({ logger: logger }));
app.use(express.json());
app.use('/api/v2/', PublicRoutesV2);
app.use(async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    // some code you dont care
    res.on('finish', () => res.locals.client.closeConnection())
    next();
})

app.use(expressMiddleware(appsignal));
app.use('/api/v2/', RoutesV2)
app.use(expressErrorHandler(appsignal))

app.use((err: Error, req: Request, res: Response, next: NextFunction): void => {
    res.status(500).json({ code: 'internal_server_error', detail: 'Something went wrong' })
})

export { app }
```

The code that breaks is a handler inside our `RoutesV2` router and in Appsignal we dont get anything useful:

![appsignal com_bitex-dot-la_sites_62260f81d2a5e49138a91043_performance_incidents_3](https://user-images.githubusercontent.com/2261869/164073291-fe196eb0-2194-4d72-8686-8ac04073d99a.png)

We would expect, just like the Rails version:
- Body received
- Parameters received
- Path

**Comment by shairyar** [comment]
Hey @matiasgarcia could you please reach out at support@appsignal.com so I can take a look into this with you and assist? Feel free to just mention this issue.

**Comment by matiasgarcia** [comment]
Hello @shairyar, thanks for taking a look at this. I just emailed support as you asked. Have a nice week!

**Comment by shairyar** [comment]
Hey @matiasgarcia we have not received any email.

**Comment by matiasgarcia** [comment]
Sent again

**Comment by shairyar** [comment]
I think we can close this after our discussion, Related: https://github.com/appsignal/appsignal-nodejs/issues/650
