### ISSUE TITLE
Express Integration: Track request body by default

### ISSUE THREAD

**Issue by matiasgarcia** [appsignal/appsignal-nodejs#650]
I am wondering if there is room for tracking the response body, automatically, in the express integration.

We are doing this manually right now, but we would prefer to this come out of the box as other integrations (i.e ruby on rails one).

```
    span.setSampleData(
        "params", {
            "url": req.path,
            "method": req.method ,
            "params": req.params,
            "body": req.body,
            "query": JSON.stringify(req.query)
        }
    )
```

I took a look at the code, and maybe, this can be added in the following line?

https://github.com/appsignal/appsignal-nodejs/blob/main/packages/express/src/middleware/index.ts#L48

For example:

Rather than

`span.setSampleData("params", { ...params, ...query })`

Do

`span.setSampleData("params", { ...params, ...query, body: req.body })`

**Comment by shairyar** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700116213

**Comment by tombruijn** [comment]
Hi @matiasgarcia, Thanks for the issue. We're aware of the problem. We're going to take a look at it, hopefully this week.

**Comment by luismiramirez** [comment]
Hey @matiasgarcia! You can find the fix in the latest [@appsignal/express](https://www.npmjs.com/package/@appsignal/express/v/1.0.30) version.

Thank you very much for your collaboration!
