### ISSUE TITLE
Update TS to 4.4

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#660]
To keep consistency with the JavaScript integration (https://github.com/appsignal/appsignal-javascript/issues/569), update this integration TypeScript dependency to 4.4.

From the linked issue:

_In TS 4.4, useUnknownInCatchVariables is activated by default if you have it configured to strict: true. Which is a good practice._

_This makes the caught variables in a try/catch block to be of the unknown type, so we need to check if the object we are catching is an error in our try/catch blocks to comply with this new rule._

## TODO

- [ ] Update TypeScript general dependency to 4.4
- [ ] Adapt try/catch blocks to check the caught variable type if needed

**Comment by tombruijn** [comment]
Are we incompatible with apps running TypeScript 4.4? Or does it not matter because we ship the transcompiled JavaScript?

It sounds like there shouldn't be a problem. But it would be good to keep up-to-date with TypeScript going forward.
