### ISSUE TITLE
I am unable to bump from 2.3.6 to 2.4.1

### ISSUE THREAD

**Issue by cegerard** [appsignal/appsignal-nodejs#684]
Hi 👋 ,

I try to bump my Appsignal node js dependency and I encounter the error below:
![image](https://user-images.githubusercontent.com/3628660/172415101-6969ac7e-0f3d-45d7-abcb-366c222083f0.png)

I also try to update both appsignal dependencies:
 "@appsignal/express": "^1.0.31",
 "@appsignal/nodejs": "^2.4.1",

I there anything missing from the last update?

**Comment by tombruijn** [comment]
Hi @cegerard, can you add the `@opentelemetry/sdk-trace-base` package to your app? `npm install @opentelemetry/sdk-trace-base`
It should have included the necessary imports during precompile, but looks like something went wrong.

**Comment by cegerard** [comment]
Hi @tombruijn.

Yes, I can do that, and if a did it works as expected. As we discuss with my team we prefer not to add a new dependency into our package.json if we are not using it.

So, for this issue, we will keep the 2.3.6 for now.

Thanks for your answer.

**Comment by tombruijn** [comment]
@cegerard that sounds like a good solution for now. I've made a "fix" in PR #685 that adds the `@opentelemetry/sdk-trace-base` as a runtime dependency to our package while we find a better solution. We've shipped this in version 2.4.2.

**Comment by tombruijn** [comment]
Closing in favor of #686.
