### ISSUE TITLE
Demo command for OpenTelemetry version

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#700]
Add a demo command following the [integration guide](https://github.com/appsignal/integration-guide/blob/main/features/cli/demo.md) guidelines.

As it states:

_The demo command line tool starts a creates example scenario and has the agent send two demo samples to the application configured in the application configuration. This is useful for our users to have some data to see on AppSignal.com and confirm the installation of our integration was successful on their system. It is automatically called in the install command line tool as well._

The current Node.js doesn't work as required, make the new one work as an independent command as in Ruby and Elixir.

**Comment by tombruijn** [comment]
It's implemented in the CLI package by Noemi and I added it to the Node.js package after the OpenTelemetry refactor. The integration guide needs to be updated https://github.com/appsignal/integration-guide/blob/main/features/cli/demo.md

**Comment by luismiramirez** [comment]
Addition to the integration guide: https://github.com/appsignal/integration-guide/pull/140
