### ISSUE TITLE
Install command automatically adds `appsignal.(js|ts)` file

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#728]
If possible, do the following:

- [x] Remove the AppSignal configuration from the CLI output.
- [x] Write a `appsignal.js` file to the root of the project with the previously printed AppSignal configuration.
  - [x] If a `src` dir exists, write the `appsignal.js` file to the `src` directory.
  - [ ] ~If a `.ts` file exists in either directory, write it as an `.ts` file. Note: The require/import statement is different for CSM and ESM.~
- [ ] ~Update the `package.json` scripts to use `--require [src/]appsignal.(j|t)s`.~
  - ~"This is entirely optional. If we do this for every script we can break things. Instead only update the "server" or "start" scripts? If this becomes too fragile, print it as instructions instead.~

**Comment by unflxw** [comment]
TO-DO:
- [ ] The installer should create `.cjs` files, not `.js` files.
- [ ] The files should not export the Appsignal client -- users should be directed to use the `Appsignal.client` method in the class.

**Comment by jeffkreeftmeijer** [comment]
Closing, as completed by https://github.com/appsignal/appsignal-javascript/pull/579. The work for Typescript support is moved to https://github.com/appsignal/appsignal-nodejs/issues/774, and the work for automatically updating `package.json` is moved to https://github.com/appsignal/appsignal-nodejs/issues/775.
