### ISSUE TITLE
Record params in Koa only when in the router middleware

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#730]
The Koa requestHook is set up to record request params as magic attributes, but it differs from the Express one in that we don't check which middleware is triggering the request hook: https://github.com/appsignal/appsignal-nodejs/blob/opentelemetry/src/client.ts#L216-L228

We need to record the parameters in the span just when in the router middleware, setting them in all the middleware spans is not needed.

**Comment by tombruijn** [comment]
Relevant issue for filtering those parameters when collected: https://github.com/appsignal/opentelemetry/issues/48

**Comment by tombruijn** [comment]
Blocked while we wait on the OpenTelemetry release.
