### ISSUE TITLE
Knex instrumentation

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#762]
Knex is a query builder used by the Bookshelf ORM.

## To do
- [x] Add instrumentation to the client by default
  - Only if the instrumentation library is part of the OpenTelemetry core or auto instrumentation package
- [x] Add extractor for OpenTelemetry spans
- [x] Add integration test for spans
- [x] Add colors and grouping to server repo
- [x] Add the instrumentation to the docs

**Comment by unflxw** [comment]
@tombruijn Added a TO-DO point to add docs to it.
