### ISSUE TITLE
FS module instrumentation

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#763]
The Node.js module that does things with the file system.

## To do
- [x] Add instrumentation to the client by default (https://github.com/appsignal/appsignal-nodejs/pull/777)
  - Only if the instrumentation library is part of the OpenTelemetry core or auto instrumentation package
- [x] Add extractor for OpenTelemetry spans (https://github.com/appsignal/appsignal-agent/pull/846)
- [x] Add integration test for spans (https://github.com/appsignal/appsignal-nodejs/pull/777)

**Comment by luismiramirez** [comment]
Reason why this issue is blocked: ttps://github.com/appsignal/appsignal-nodejs/pull/777#issuecomment-1295054358
