### ISSUE TITLE
Restify instrumentation

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#787]
Web framework.

https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-restify

## To do
- [x] Add instrumentation to the client by default
  - Only if the instrumentation library is part of the OpenTelemetry core or auto instrumentation package
- [x] Add extractor for OpenTelemetry spans
- [x] Add integration test for spans
- [x] Add docs
- [x] Add `requestHook` config option to restify instrumentation: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1312
- [x] Update restify instrumentation with requestHook config option to set request parameters

**Comment by tombruijn** [comment]
Once PR https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1312 has been merged and released anyone can pick up the last point to add the requestHook config option.

**Comment by tombruijn** [comment]
Tracking issue/PR for the new OpenTelemetry release with the restify requestHook config option: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1301
