### ISSUE TITLE
ignoredActions not working in v3

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#788]
Report from a customer:

_It does look like there may be a slight regression though with `ignoredActions`. I have set up a custom action name ("APPSIGNAL_IGNORE"), that I use for things we don't need metrics on. When the optional extra `span` argument feature was added, it seems that `setName` would apply to the current active span, so I changed the relevant calls to use `setRootName`, but the action still seems to be sent along and shows up in the "Issue List"._

**Comment by tombruijn** [comment]
Do you have an intercom link?

And this probably because we check the root action name and not the to-be-hoisted action name in magic attributes on child spans.

**Comment by luismiramirez** [comment]
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700154694#part_id=comment-16410700154694-17774397502
