### ISSUE TITLE
Use operation names as root span incident name in GraphQL instrumentation

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#791]
As suggested in [this Intercom conversation](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700151267) and [this Slack conversation](https://appsignal.slack.com/archives/C024TUL49/p1668143580972729), it would be useful to use the GraphQL operation name as the root name, in order to group the queries by name in the performance actions view.

We may also want to improve on the existing GraphQL extractor in general. [The current implementation](https://github.com/appsignal/appsignal-agent/blob/main/common/src/opentelemetry/extractors/nodejs/graphql.rs) just seeks to provide feature parity with 2.4 by obtaining the query for the execute span. All the non-execute kinds of spans (parse, validate, resolve) are just being converted to information-less "operation.graphql" spans. We should display those spans in a way that gives more information to the user.

**Comment by tombruijn** [comment]
- [ ] Let's set the operation name as the root span name.
  - [ ] If no operation name is set, don't set a magic attribute for the name.
- [ ] Let's set the namespace to `graphql` by default

Both items using magic attributes in the extractor.

**Comment by tombruijn** [comment]
@unflxw On PR https://github.com/appsignal/appsignal-agent/pull/853 you said we should look at the "operation.graphql" span names. The GraphQL instrumentation span names already have this kind of information, but in the wrong order. We could reorder the sub strings that make up the span names to do this.

WDYT, or are there other scenarios I don't know that can break like that?

Example of the reordering:

- "graphql.execute" -> "execute.graphql"
- "graphql.resolve" -> "resolve.graphql"
- "graphql.validate" -> "validate.graphql"
- "graphql.parse" -> "parse.graphql"

**Comment by unflxw** [comment]
@tombruijn That sounds good to me. We do similar things for other instrumentations already.
