### ISSUE TITLE
Update `@opentelemetry/api`, remove `@opentelemetry/api-metrics`

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#822]
On `npm i @appsignal/nodejs`:

```npm WARN deprecated @opentelemetry/api-metrics@0.33.0: Please use @opentelemetry/api >= 1.3.0```

We should update our dependencies.

**Comment by tombruijn** [comment]
I think this is because of our [local overrides](https://github.com/appsignal/appsignal-nodejs/blob/dcf78f18d2a89cf29c051474ea9902713e474b8b/package.json#L43). Package `@opentelemetry/instrumentation` version 0.34.0 doesn't have this dependency anymore. Can we remove the override @unflxw ?

**Comment by unflxw** [comment]
Probably! If the tests pass without it then we're good.

**Comment by tombruijn** [comment]
@unflxw can you do a quick test of that?

**Comment by unflxw** [comment]
It's not the overrides' fault (though I'll submit a PR to remove them anyway)

Prisma instrumentation has not updated its dependencies on `@opentelemetry/instrumentation` and `@opentelemetry/api` for a while -- the first one brings in the deprecated `@opentelemetry/api-metrics`.

Submitted a PR to Prisma: https://github.com/prisma/prisma/pull/17198

**Comment by tombruijn** [comment]
Prisma PR and our PR merged. Closing.

**Comment by unflxw** [comment]
@tombruijn Should we keep this open until there's a Prisma release that we can upgrade our dependency?

**Comment by unflxw** [comment]
Closed by #842.
