### ISSUE TITLE
Add Pino support to the logger

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#828]
Like Winston (see #821) Pino also supports transports, so we can probably tie it into the logging API in a similar way.

In the [Intercom thread](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700167053) from #821., the customer mentioned Pino would also be interesting to have.

## To do

- [x] Implement Pino transport (see our [Winston transport documentation](https://docs.appsignal.com/logging/platforms/integrations/nodejs.html#usage-with-winston) and [Pino's transport documentation](https://github.com/pinojs/pino/blob/master/docs/transports.md) for reference) -> https://github.com/appsignal/appsignal-nodejs/pull/1134
- [x] Document it next to the [Winston transport documentation](https://docs.appsignal.com/logging/platforms/integrations/nodejs.html#usage-with-winston) -> https://github.com/appsignal/appsignal-docs/pull/2193
- [x] Notify user who requested it.
- [x] Request the addition to [Pino known transports list](https://github.com/pinojs/pino/blob/master/docs/transports.md#pino-v7-compatible) -> https://github.com/pinojs/pino/pull/2065

**Comment by tombruijn** [comment]
@unflxw can you add a section with a To do list that describes in detail the steps someone has to take to complete this issue?

**Comment by luismiramirez** [comment]
Moving this to backlog until we're able to log via HTTP.

Pino transports are run as worker threads. We can't pass the client safely as an argument to the worker initialization, and as we're using TS, making users write a built file path is not an ideal solution.

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700256468?view=List (private link)

**Comment by mgm1313** [comment]
Is this still being considered? Since the start of this thread, Pino has grown closer to Winston in terms of adoption and is still [faster](https://github.com/pinojs/pino/blob/main/docs/benchmarks.md) than Winston, which is why we prefer it in our stack.

![pino,winston](https://github.com/user-attachments/assets/c9e2f601-7635-4bf4-8417-b04dbde2c07a)

I found this transporter in user land https://github.com/duailibe/pino-appsignal-transport, but official support would still be awesome! :)

**Comment by luismiramirez** [comment]
@mgm1313 hey, thank you!

Yes, we're considering this and we're moving it ahead soon.

**Comment by kamilcglr** [comment]
Hello everyone, I would also like to see pino supported. I use Adonis and the default logger is pino. Thanks in advance.

**Comment by flozdra** [comment]
Hi there, same here. We also use AdonisJS so it would be awesome to have official support

**Comment by luismiramirez** [comment]
The Pino transport has been released!

It's available in [v3.5.1](https://www.npmjs.com/package/@appsignal/nodejs/v/3.5.1)

You can find the docs here: https://docs.appsignal.com/logging/platforms/integrations/nodejs.html#usage-with-pino

Feel free to reach out for help and/or suggestions!
