### ISSUE TITLE
Add support for Remix

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-nodejs#863]
There is an [opentelemetry-instrumentation-remix package](https://www.npmjs.com/package/opentelemetry-instrumentation-remix), which looks like a good candidate to use in order to provide out-of-the-box integration with [Remix](https://remix.run/).

## To do

- [x] Send in an upstream PR to fix the error reporting to use events (not use attributes) -- in progress: https://github.com/justindsmith/opentelemetry-instrumentations-js/pull/37
- [x] Adding support in the form of an extractor in the agent. - https://github.com/appsignal/appsignal-agent/pull/1041
- [x] Docs: https://github.com/appsignal/appsignal-docs/pull/1439

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700172914 (Private link)

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/unassigned/conversation/16410700220790 (Private link)

**Comment by tombruijn** [comment]
https://github.com/justindsmith/opentelemetry-instrumentations-js/pull/37

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700232861 (Private link)

**Comment by luismiramirez** [comment]
This change (https://github.com/justindsmith/opentelemetry-instrumentations-js/pull/41/files) is required to release a proper instrumentation. I'll watch it and will keep working on this once published

**Comment by luismiramirez** [comment]
@shairyar The customers can be notified.

The docs page is here: https://docs.appsignal.com/nodejs/3.x/integrations/remix.html

**Comment by luismiramirez** [comment]
Customers notified!
