### ISSUE TITLE
Implement support for Bull instrumentation

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#873]
We know [some of our users use it](https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/search/conversations/16410700133028?q=bull&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all) and have written custom instrumentation for it, and a [non-contrib OpenTelemetry instrumentation](https://github.com/jenniferplusplus/opentelemetry-instrumentation-bullmq) for it exists. We could add support for it, and it would line up neatly with [our blog post plans](https://3.basecamp.com/4738529/buckets/18523847/messages/5976031401) as well.

**Comment by cjurjiu** [comment]
Looking forward to have this. Any update on this one? Thanks! 🙏

**Comment by unflxw** [comment]
@cjurjiu Support for BullMQ (not the earlier, discontinued Bull!) was implemented in version 3.4.5 of the AppSignal for Node.js integration: https://docs.appsignal.com/nodejs/3.x/integrations/bullmq.html
