### ISSUE TITLE
Report on `appsignal.cjs` in the diagnose

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#882]
The diagnose tool should look for this file at the locations where it's expected (`appsignal.cjs` or `src/appsignal.cjs`).

Ideally we'd like the configuration added to the `Appsignal` initialiser in this file to be reported in the diagnose report. To report on the configuration, the diagnose tool [creates a new configuration object](https://github.com/appsignal/appsignal-nodejs/blob/63b260268fdbb80eac83f8cfb53e77d7e54b53cf/src/diagnose.ts#L37), which does not have any values for the "initial" source.

Instead, the diagnose tool could attempt to require this `appsignal.cjs` file. When required, it will create an instance of `Appsignal`, which will write itself the global `Appsignal.client` object. We could then ask this global instance for its configuration object, and do the report based on that object.

Finally, since sometimes users don't have a plain `appsignal.cjs` file (for example, if they have an `appsignal.ts` file which ends up somewhere else as `dist/appsignal.js`) we could have a `--config` option so users can specify where this file actually is. Not sure if this is worth the effort.

## To do

- [x] Make the diagnose report on the presence/absence of `appsignal.cjs` and its contents https://github.com/appsignal/appsignal-nodejs/pull/884.
- [x] If the file exists, report on the config that is provided by it. https://github.com/appsignal/appsignal-nodejs/pull/885
- [ ] ~Add a `--config` option to the diagnose report to indicate the path to the config file.~

(This to do list is kind of a wish list -- if any of these items turn out to be too difficult, do the pragmatic thing and drop them)

**Comment by tombruijn** [comment]
> Instead, the diagnose tool could attempt to require this appsignal.cjs file. When required, it will create an instance of Appsignal, which will write itself the global Appsignal.client object. We could then ask this global instance for its configuration object, and do the report based on that object.

We should avoid starting the AppSignal extension, which it does automatically in the client constructor.
We can set an env var like `APPSIGNAL_DIAGNOSE=true` and it won't start the extension, OpenTelemetry, minutely probes, etc. in that case. It only loads the config.

**Comment by luismiramirez** [comment]
First PR checks for the presence of the file. Now I'm working on checking its contents and config values with Tom's proposal. If it gets too complicated/not-clean-enough I'll skip it and do the `--config` flag addition which should be more straightforward.

**Comment by luismiramirez** [comment]
I'm dropping out the `--config` flag. It's taking too much time, so I'll extract it to a new issue for the future. I don't see it as critical as our docs suggest users to use the `appsignal.cjs` way of initializing the client.

The main problem I've encountered is that the current `Config` and `Diagnose` classes need to interact too much between them to know if the provided custom file is present, meaning that we somehow must store `Diagnose` data into the `Config` object.
