### ISSUE TITLE
Check whether Prisma 5.0.0 works

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#913]
`@prisma/client` and `@prisma/instrumentation` version `5.0.0` were just released.

To do
===

- [x] Check whether it works well: not yet
- [ ] Fix it if it doesn't

**Comment by tombruijn** [comment]
I assume your comment was 'resolved' in a way in the test setups PR? https://github.com/appsignal/test-setups/pull/130
