### ISSUE TITLE
Update @appsignal/nodejs dependencies (@opentelemetry/instrumentation)

### ISSUE THREAD

**Issue by Fernandomr88** [appsignal/appsignal-nodejs#943]
I need to fix this issue with nodejs package. There's this dependency that needs to be updated:

`@opentelemetry/instrumentation to version 0.41.2 or later`

Also, there's a major incompatibility of opentelemetry with current fastify versions and it will be fixed (supposely) on this PR:

https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1679

So, that needs attention

<img width="1139" alt="image" src="https://github.com/appsignal/appsignal-nodejs/assets/14304128/6a7b8714-6bf5-4615-9e42-ab3671934a5f">

<img width="1473" alt="image" src="https://github.com/appsignal/appsignal-nodejs/assets/14304128/4b0c94a7-3bf2-4532-9901-b22ffa0f1dbe">

**Comment by tombruijn** [comment]
Made a PR with a fix in #944.
