### ISSUE TITLE
Update dependency [instrumentation-fastify: v0.32.3]

### ISSUE THREAD

**Issue by Fernandomr88** [appsignal/appsignal-nodejs#947]
Yesterday opentelemetry [updated](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1679) their package to fix some deprecated implementation over fastify, that deprecation is producing thousands of errors when using appsignal since it is depending on the previous version yet 

https://github.com/appsignal/appsignal-nodejs/blob/6f5e32fa59c791082f5b1b5729ad8acc16ef37c8/package.json#L17

Can you guys update to `instrumentation-fastify: v0.32.3`?

![image](https://github.com/appsignal/appsignal-nodejs/assets/14304128/14d8d24f-2977-4609-9709-4280b1373b6a)

Thanks

**Comment by Fernandomr88** [comment]
Weird enough I updated the package manually on package-lock.json and the error kept on happening.

**Comment by luismiramirez** [comment]
Hi @Fernandomr88!

I'm currently working on updating the dependency to "^0.32.3"

For a Fastify 4.10.2 application, I get this message:
```
FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`
```

That's normal because the `Request` object for that Fastify version doesn't have the `routeSchema` or `routeConfig` property yet, so it falls back to the deprecated one (`context`) instead. This is the intended behaviour of the OpenTelemetry package update.

I'm not able to get the `routerPath` warning, though. What Fastify version are you using?

**Comment by Fernandomr88** [comment]
> Hi @Fernandomr88!
> 
> 
> 
> I'm currently working on updating the dependency to "^0.32.3"
> 
> 
> 
> For a Fastify 4.10.2 application, I get this message:
> 
> ```
> 
> FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`
> 
> ```
> 
> 
> 
> That's normal because the `Request` object for that Fastify version doesn't have the `routeSchema` or `routeConfig` property yet, so it falls back to the deprecated one (`context`) instead. This is the intended behaviour of the OpenTelemetry package update.
> 
> 
> 
> I'm not able to get the `routerPath` warning, though. What Fastify version are you using?

Hey, im using NestJS. Which uses this package:   
"@nestjs/platform-fastify": "^10.2.6",

That depends on **fastify 4.23.2**. Below it's dependencies:

"dependencies": {
    "@fastify/cors": "8.3.0",
    "@fastify/formbody": "7.4.0",
    "@fastify/middie": "8.3.0",
    "fastify": "4.23.2",
    "light-my-request": "5.10.0",
    "path-to-regexp": "3.2.0",
    "tslib": "2.6.2"
  },
  "peerDependencies": {
    "@fastify/static": "^6.0.0",
    "@fastify/view": "^7.0.0 || ^8.0.0",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0"
  },

**Comment by luismiramirez** [comment]
@Fernandomr88 

Hi there!

The v3.0.24 package already has the update to be compatible with Fastify v5
