### ISSUE TITLE
AppSignal logging a lot of fastify deprecation logs

### ISSUE THREAD

**Issue by Fernandomr88** [appsignal/appsignal-nodejs#961]
So, this is my console since I have started to use AppSignal, 2 months ago.

I'm using the `"@appsignal/nodejs": "^3.0.24"` version, and NestJS.
It logs this once every minute or more:

`[FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.`

<img width="1091" alt="image" src="https://github.com/appsignal/appsignal-nodejs/assets/14304128/b4c2c5bc-1964-4898-bea9-471f3d8436e4">

Dependencies:
```
    "@appsignal/nodejs": "^3.0.24",
    "@fastify/multipart": "^8.0.0",
    "@fastify/static": "^6.11.2",
    "@nestjs/bull": "^10.0.1",
    "@nestjs/common": "^10.2.6",
    "@nestjs/core": "^10.2.6",
    "@nestjs/platform-fastify": "^10.2.6",
```

**Comment by Fernandomr88** [comment]
I even created an issue for an update on dependencies but that didnt solve that issue.

https://github.com/appsignal/appsignal-nodejs/issues/947

**Comment by unflxw** [comment]
Which `fastify` version are you using @Fernandomr88? (the dependencies shown include `@fastify/static` and `@fastify/multipart`, but not Fastify itself)

A workaround would be to downgrade to the Fastify version before these warnings were added.

**Comment by Fernandomr88** [comment]
> Which `fastify` version are you using @Fernandomr88? (the dependencies shown include `@fastify/static` and `@fastify/multipart`, but not Fastify itself)
> 
> A workaround would be to downgrade to the Fastify version before these warnings were added.

4.23.2

I don't see that as a workaround since I'm not depending directly on fastify but on packages (such as @nestjs/platform-fastify) that depend on fastify.

**Comment by unflxw** [comment]
> I don't see that as a workaround since I'm not depending directly on fastify but on packages (such as @nestjs/platform-fastify) that depend on fastify.

I see! May I suggest an [override](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides)? With overrides, you can force your dependencies to use specific versions of their dependencies. On your `package.json`, add the following:

```js
{
  // ...
  "overrides": {
    "fastify": "4.15.0"
  }
}
```

You could also, of course, downgrade `@nestjs/fastify-platform` to the desired version.

The warning first appeared in version `4.16.0` ([see commit](https://github.com/fastify/fastify/commit/7ffefaf272e1b0da5c0889e0c7c54ac8203756f2)) so I would suggest pinning it to version `4.15.0` to get rid of the warnings.

> If I disable AppSignal the errors stop, so the issue is coming from AppSignal itself and not third party packages.

Correct! Well, specifically, from the `@opentelemetry/instrumentation-fastify` dependency, which we bring in. But the warning is emitted by `fastify` through something that our instrumentation does.

**Comment by Fernandomr88** [comment]
> > I don't see that as a workaround since I'm not depending directly on fastify but on packages (such as @nestjs/platform-fastify) that depend on fastify.
> 
> I see! May I suggest an [override](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides)? With overrides, you can force your dependencies to use specific versions of their dependencies. On your `package.json`, add the following:
> 
> ```js
> {
>   // ...
>   "overrides": {
>     "fastify": "4.15.0"
>   }
> }
> ```
> 
> The warning first appeared in version `4.16.0` ([see commit](https://github.com/fastify/fastify/commit/7ffefaf272e1b0da5c0889e0c7c54ac8203756f2)) so I would suggest pinning it to version `4.15.0` to get rid of the warnings.
> 
> > If I disable AppSignal the errors stop, so the issue is coming from AppSignal itself and not third party packages.
> 
> Correct! Well, specifically, from the `@opentelemetry/instrumentation-fastify` dependency, which we bring in. But the warning is emitted by `fastify` through something that our instrumentation does.

So the correct solution to this is to talk to @opentelemetry guys and see what can be done, right? I mean, depending on an older version of fastify (sept 2022) may introduce bugs and/or vulnerabilities to my server that I don't desire.

**Comment by unflxw** [comment]
@Fernandomr88 That's part of it, yes. There is [this GitHub issue upstream](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1757) where they're looking into solving this issue and suggesting other workarounds.

**Comment by unflxw** [comment]
Also, note that you can use the `NODE_NO_WARNINGS` environment variable to silence the warnings: https://github.com/fastify/process-warning#suppressing-warnings

**Comment by Fernandomr88** [comment]
> @Fernandomr88 That's part of it, yes. There is [this GitHub issue upstream](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1757) where they're looking into solving this issue and suggesting other workarounds.

I'll try to contribute there, in the meanwhile I'll use that env to suppress the warning.

Also, in my opinion this issue should remain open until this problem is solved. AppSignal is the factor to produce those logs and this issue should be in your radar until solved by open-telemetry

**Comment by Fernandomr88** [comment]
@unflxw seems like the fix is being merged.

https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1757#issuecomment-1832493122

**Comment by shairyar** [comment]
https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700257719?view=List (private link)
