### ISSUE TITLE
Failed to boot agent: bad path

### ISSUE THREAD

**Issue by tomaspinho** [appsignal/appsignal-nodejs#97]
Hello again!

The latest version of this package fails to boot the AppSignal agent with:

```
[2020-04-13T09:06:32 (extension) #6][Error] Failed to boot agent at '/usr/app/node_modules/@appsignal/nodejs/node_modules/@appsignal/nodejs-ext/ext/appsignal-agent': No such file or directory (os error 2)
```
The agent binary is actually in `/usr/app/node_modules/@appsignal/nodejs-ext/ext/appsignal-agent`.

I believe this path discovery is implemented in the proprietary extension's binary, for which we don't have access to the source code. There also seems to be a private environment variable `_APPSIGNAL_AGENT_PATH` that would let us override this, however the package doesn't pass it (doesn't support it).

The package was installed with 
```
npm --version
6.14.4
node --version
v12.16.2
```
As the paths may differ between nodejs versions - older NPM versions do not flatten the package tree, AFAIK

**Comment by tomaspinho** [comment]
A hack that makes it work is symlinking:
```
ln -s /usr/app/node_modules/@appsignal /usr/app/node_modules/@appsignal/nodejs/node_modules/
```

**Comment by xadamy** [comment]
Thanks for this @tomaspinho , I see what the problem is here. I'll update the issue as soon as I can!

**Comment by xadamy** [comment]
@tomaspinho Thank you again for your patience with this. 🙏 

I have now pushed version `0.3.1` which should load the agent from the correct path when installed via `npm` (it would only install with `yarn` + workspaces mode before this change). Please give it a try and let me know if there are any more issues!
