### ISSUE TITLE
Fastify instrumentation may not report errors?

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#975]
We saw an issue during a call where a customer ([Intercom link](https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/all/conversation/16410700278096#part_id=comment-16410700278096-21909547734)) did not see errors reported from their Fastify application's error handlers automatically. (This customer was affected by #974, but the issue persisted _after_ the workaround was applied)

Another workaround was used, in which a custom Fastify error handler was used to manually forward errors to AppSignal.

To do
====

- [ ] Attempt to reproduce in our test setup?
- If reproduced:
  - [ ] Document custom error handler
  - [ ] Report to upstream OpenTelemetry instrumentation

**Comment by brogeby** [comment]
Would you be able to provide the solution for the custom fastify error handler? I'm experience the same issue and would like to try the given solution.

**Comment by luismiramirez** [comment]
This is fixed in newer versions of @appsignal/nodejs (^3.4.8).
