### ISSUE TITLE
Appsignal cannnot be configured via environment  variables, in node

### ISSUE THREAD

**Issue by elmerbulthuis** [appsignal/appsignal-nodejs#980]
I have the followig environment variables set:
```sh
APPSIGNAL_APP_ENV=local
APPSIGNAL_APP_NAME=nwd-api-server
APPSIGNAL_PUSH_API_KEY=secret-guid
```

I have this in the entrypoint of my program:
```typescript
const appsignal = new Appsignal({});
```

When I start my program I get an error (AppSignal not starting, no valid configuration found) telling met that the configuration is invalid.

If i change the entrypoint of my application to
```typescript
const appsignal = new Appsignal({
    active: true,
    environment: process.env.APPSIGNAL_APP_ENV,
    name: process.env.APPSIGNAL_APP_NAME,
    pushApiKey: process.env.APPSIGNAL_PUSH_API_KEY,
  });
```

everything works as expected

**Comment by unflxw** [comment]
Hi @elmerbulthuis!

Both ways should work. Could you tell us more about how you're setting the environment variables?

**Comment by elmerbulthuis** [comment]
I tested it by setting the environment variables via a launch configuration in vscode.

**Comment by unflxw** [comment]
Hi @elmerbulthuis,

I can confirm that environment variables do work as expected. The issue must lie in how the environment variables are passed from VSCode. Feel free to reach out on support@appsignal.com. Provide a link to this issue.
